/**
 * Generated by "@vuepress/internal-routes"
 */

import { injectComponentOption, ensureAsyncComponentsLoaded } from '@app/util'
import rootMixins from '@internal/root-mixins'
import GlobalLayout from "/Users/zouyu/Desktop/vuepress-starter/node_modules/@vuepress/core/lib/client/components/GlobalLayout.vue"

injectComponentOption(GlobalLayout, 'mixins', rootMixins)
export const routes = [
  {
    name: "v-eaf154bc",
    path: "/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-eaf154bc").then(next)
    },
  },
  {
    path: "/index.html",
    redirect: "/"
  },
  {
    name: "v-48cfbd39",
    path: "/about/2019_year_end.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-48cfbd39").then(next)
    },
  },
  {
    name: "v-fa01d5b4",
    path: "/about/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-fa01d5b4").then(next)
    },
  },
  {
    path: "/about/index.html",
    redirect: "/about/"
  },
  {
    name: "v-1c79b5f9",
    path: "/brower/renderTree.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-1c79b5f9").then(next)
    },
  },
  {
    name: "v-034e5059",
    path: "/database/choice.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-034e5059").then(next)
    },
  },
  {
    name: "v-2dbc8d2e",
    path: "/database/detail-redis1.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-2dbc8d2e").then(next)
    },
  },
  {
    name: "v-7306d1e7",
    path: "/database/detail-redis2.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-7306d1e7").then(next)
    },
  },
  {
    name: "v-06282b36",
    path: "/database/detail-redis3.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-06282b36").then(next)
    },
  },
  {
    name: "v-cacbb322",
    path: "/database/mysql/baseFrame.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-cacbb322").then(next)
    },
  },
  {
    name: "v-e7493e7e",
    path: "/database/mysql/logSystem.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-e7493e7e").then(next)
    },
  },
  {
    name: "v-799c6ef9",
    path: "/database/mysql/optimize.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-799c6ef9").then(next)
    },
  },
  {
    name: "v-7d917239",
    path: "/database/mysql/writeSql.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-7d917239").then(next)
    },
  },
  {
    name: "v-0995f732",
    path: "/database/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-0995f732").then(next)
    },
  },
  {
    path: "/database/index.html",
    redirect: "/database/"
  },
  {
    name: "v-4672ab0e",
    path: "/interview/js10.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-4672ab0e").then(next)
    },
  },
  {
    name: "v-370b7719",
    path: "/interview/css.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-370b7719").then(next)
    },
  },
  {
    name: "v-21d68519",
    path: "/interview/notes.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-21d68519").then(next)
    },
  },
  {
    name: "v-015b2d3e",
    path: "/interview/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-015b2d3e").then(next)
    },
  },
  {
    path: "/interview/index.html",
    redirect: "/interview/"
  },
  {
    name: "v-36d5d319",
    path: "/interview/rewriteJs.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-36d5d319").then(next)
    },
  },
  {
    name: "v-5e249ae7",
    path: "/interview/unique.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-5e249ae7").then(next)
    },
  },
  {
    name: "v-10e6468e",
    path: "/interview/vue.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-10e6468e").then(next)
    },
  },
  {
    name: "v-0f85b128",
    path: "/node-zy/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-0f85b128").then(next)
    },
  },
  {
    path: "/node-zy/index.html",
    redirect: "/node-zy/"
  },
  {
    name: "v-079e2011",
    path: "/node-zy/path.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-079e2011").then(next)
    },
  },
  {
    name: "v-df6e1f4a",
    path: "/node-zy/stream.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-df6e1f4a").then(next)
    },
  },
  {
    name: "v-3a513799",
    path: "/node/APIGateway.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-3a513799").then(next)
    },
  },
  {
    name: "v-2318913b",
    path: "/node/AsyncIO.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-2318913b").then(next)
    },
  },
  {
    name: "v-70c26a12",
    path: "/node/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-70c26a12").then(next)
    },
  },
  {
    path: "/node/index.html",
    redirect: "/node/"
  },
  {
    name: "v-87f4d64e",
    path: "/node/buffer.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-87f4d64e").then(next)
    },
  },
  {
    name: "v-a0e6d78e",
    path: "/node/errors.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-a0e6d78e").then(next)
    },
  },
  {
    name: "v-dd448c0e",
    path: "/node/event_loop.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-dd448c0e").then(next)
    },
  },
  {
    name: "v-02aacdf9",
    path: "/node/events.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-02aacdf9").then(next)
    },
  },
  {
    name: "v-6e9f767f",
    path: "/node/module_fs.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-6e9f767f").then(next)
    },
  },
  {
    name: "v-cb3ceeae",
    path: "/node/npm.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-cb3ceeae").then(next)
    },
  },
  {
    name: "v-1916abd9",
    path: "/node/overflow.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-1916abd9").then(next)
    },
  },
  {
    name: "v-074a5179",
    path: "/node/path.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-074a5179").then(next)
    },
  },
  {
    name: "v-573684d9",
    path: "/node/processAndThread.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-573684d9").then(next)
    },
  },
  {
    name: "v-ac9d7246",
    path: "/node/queue.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-ac9d7246").then(next)
    },
  },
  {
    name: "v-222a7cd9",
    path: "/node/stream.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-222a7cd9").then(next)
    },
  },
  {
    name: "v-e6f459ce",
    path: "/node/what.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-e6f459ce").then(next)
    },
  },
  {
    name: "v-3439a0ad",
    path: "/recommend/book.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-3439a0ad").then(next)
    },
  },
  {
    name: "v-3b49be0e",
    path: "/recommend/project.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-3b49be0e").then(next)
    },
  },
  {
    name: "v-568a1ef2",
    path: "/tags/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-568a1ef2").then(next)
    },
  },
  {
    path: "/tags/index.html",
    redirect: "/tags/"
  },
  {
    name: "v-53b30d47",
    path: "/typescript/interface.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-53b30d47").then(next)
    },
  },
  {
    name: "v-72ac281c",
    path: "/webframe/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-72ac281c").then(next)
    },
  },
  {
    path: "/webframe/index.html",
    redirect: "/webframe/"
  },
  {
    name: "v-db5130f2",
    path: "/webframe/css/1.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-db5130f2").then(next)
    },
  },
  {
    name: "v-4e72c11c",
    path: "/webframe/css/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-4e72c11c").then(next)
    },
  },
  {
    path: "/webframe/css/index.html",
    redirect: "/webframe/css/"
  },
  {
    name: "v-6cadae39",
    path: "/webframe/css/render.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-6cadae39").then(next)
    },
  },
  {
    name: "v-33ca55dc",
    path: "/webframe/es6/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-33ca55dc").then(next)
    },
  },
  {
    path: "/webframe/es6/index.html",
    redirect: "/webframe/es6/"
  },
  {
    name: "v-4db130d5",
    path: "/webframe/es6/async-await.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-4db130d5").then(next)
    },
  },
  {
    name: "v-c2a60a8e",
    path: "/webframe/es6/classInherit.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-c2a60a8e").then(next)
    },
  },
  {
    name: "v-7ad91ba9",
    path: "/webframe/es6/promise.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-7ad91ba9").then(next)
    },
  },
  {
    name: "v-552ce47e",
    path: "/webframe/html/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-552ce47e").then(next)
    },
  },
  {
    path: "/webframe/html/index.html",
    redirect: "/webframe/html/"
  },
  {
    name: "v-378a030c",
    path: "/webframe/javascript/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-378a030c").then(next)
    },
  },
  {
    path: "/webframe/javascript/index.html",
    redirect: "/webframe/javascript/"
  },
  {
    name: "v-43960319",
    path: "/webframe/javascript/closure.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-43960319").then(next)
    },
  },
  {
    name: "v-142e22e3",
    path: "/webframe/javascript/copy.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-142e22e3").then(next)
    },
  },
  {
    name: "v-40d5d845",
    path: "/webframe/javascript/datatype.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-40d5d845").then(next)
    },
  },
  {
    name: "v-97e69dce",
    path: "/webframe/javascript/es6WidelyUsed.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-97e69dce").then(next)
    },
  },
  {
    name: "v-092fd399",
    path: "/webframe/javascript/exports.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-092fd399").then(next)
    },
  },
  {
    name: "v-057c5cb2",
    path: "/webframe/javascript/higherFunc.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-057c5cb2").then(next)
    },
  },
  {
    name: "v-b7adee0e",
    path: "/webframe/javascript/prototype.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-b7adee0e").then(next)
    },
  },
  {
    name: "v-6a89a78e",
    path: "/webframe/javascript/recircleFun.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-6a89a78e").then(next)
    },
  },
  {
    name: "v-84983526",
    path: "/webframe/javascript/scoped.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-84983526").then(next)
    },
  },
  {
    name: "v-7ac73f51",
    path: "/webframe/javascript/this.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-7ac73f51").then(next)
    },
  },
  {
    name: "v-52d1902a",
    path: "/webframe/javascript/unique.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-52d1902a").then(next)
    },
  },
  {
    name: "v-304c8972",
    path: "/webframe/react/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-304c8972").then(next)
    },
  },
  {
    path: "/webframe/react/index.html",
    redirect: "/webframe/react/"
  },
  {
    name: "v-041f72e4",
    path: "/webframe/tool/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-041f72e4").then(next)
    },
  },
  {
    path: "/webframe/tool/index.html",
    redirect: "/webframe/tool/"
  },
  {
    name: "v-69aa3fef",
    path: "/webframe/tool/chrome.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-69aa3fef").then(next)
    },
  },
  {
    name: "v-faa79fce",
    path: "/webframe/tool/git.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-faa79fce").then(next)
    },
  },
  {
    name: "v-ac75dc4e",
    path: "/webframe/tool/node-versions.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-ac75dc4e").then(next)
    },
  },
  {
    name: "v-5e31e419",
    path: "/webframe/tool/shell.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-5e31e419").then(next)
    },
  },
  {
    name: "v-19f272a5",
    path: "/webframe/tool/vuepressBlog.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-19f272a5").then(next)
    },
  },
  {
    name: "v-7e68ea66",
    path: "/webframe/vue/messageWays.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-7e68ea66").then(next)
    },
  },
  {
    name: "v-3a3c125c",
    path: "/webframe/vue/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-3a3c125c").then(next)
    },
  },
  {
    path: "/webframe/vue/index.html",
    redirect: "/webframe/vue/"
  },
  {
    path: '*',
    component: GlobalLayout
  }
]