/**
 * Generated by "@vuepress/internal-site-data"
 */
export const siteData = {
  "title": "",
  "description": "",
  "base": "/",
  "headTags": [],
  "pages": [
    {
      "title": "Home",
      "frontmatter": {
        "home": true,
        "actionText": "开始阅读 →",
        "actionLink": "/node/",
        "features": [
          {
            "title": "day day up",
            "details": "记录每一天的进步, 一分耕耘，一分收获."
          },
          {
            "title": "鱼儿的成长指南",
            "details": "专注 Node.js 技术栈分享，从 前端 到 Node.js 再到 后端数据库，祝您成为优秀的高级 Node.js 全栈工程师"
          },
          {
            "title": "koala3",
            "details": "一个有趣的且乐于分享的人。座右铭：今天未完成的，明天更不会完成。"
          }
        ]
      },
      "regularPath": "/",
      "relativePath": "README.md",
      "key": "v-eaf154bc",
      "path": "/",
      "headers": [
        {
          "level": 3,
          "title": "博客技术栈目录",
          "slug": "博客技术栈目录"
        },
        {
          "level": 3,
          "title": "技术栈预览图",
          "slug": "技术栈预览图"
        },
        {
          "level": 3,
          "title": "参与贡献",
          "slug": "参与贡献"
        }
      ]
    },
    {
      "title": "你会成为你想成为的那个人 | 考拉的年终总结",
      "frontmatter": {
        "title": "你会成为你想成为的那个人 | 考拉的年终总结",
        "date": "2020-01-02T00:00:00.000Z",
        "tags": [
          "个人"
        ]
      },
      "regularPath": "/about/2019_year_end.html",
      "relativePath": "about/2019_year_end.md",
      "key": "v-48cfbd39",
      "path": "/about/2019_year_end.html",
      "headers": [
        {
          "level": 2,
          "title": "为什么选择考拉作为我的 IP ？",
          "slug": "为什么选择考拉作为我的-ip"
        },
        {
          "level": 3,
          "title": "考拉的样子",
          "slug": "考拉的样子"
        },
        {
          "level": 3,
          "title": "考拉的习性",
          "slug": "考拉的习性"
        },
        {
          "level": 3,
          "title": "考拉的寿命",
          "slug": "考拉的寿命"
        },
        {
          "level": 2,
          "title": "这一年我究竟做了什么？",
          "slug": "这一年我究竟做了什么"
        },
        {
          "level": 3,
          "title": "工作转变",
          "slug": "工作转变"
        },
        {
          "level": 3,
          "title": "学习成长",
          "slug": "学习成长"
        },
        {
          "level": 3,
          "title": "掘金写文",
          "slug": "掘金写文"
        },
        {
          "level": 3,
          "title": "公众号",
          "slug": "公众号"
        },
        {
          "level": 3,
          "title": "部分原创文章汇总",
          "slug": "部分原创文章汇总"
        },
        {
          "level": 3,
          "title": "生活",
          "slug": "生活"
        },
        {
          "level": 2,
          "title": "一点建议(送给大家，也送给自己)",
          "slug": "一点建议-送给大家-也送给自己"
        },
        {
          "level": 2,
          "title": "展望2020",
          "slug": "展望2020"
        },
        {
          "level": 3,
          "title": "技术提升",
          "slug": "技术提升"
        },
        {
          "level": 3,
          "title": "生活",
          "slug": "生活-2"
        },
        {
          "level": 3,
          "title": "要坚持的事",
          "slug": "要坚持的事"
        },
        {
          "level": 2,
          "title": "最后",
          "slug": "最后"
        }
      ]
    },
    {
      "title": "目录",
      "frontmatter": {},
      "regularPath": "/about/",
      "relativePath": "about/README.md",
      "key": "v-fa01d5b4",
      "path": "/about/",
      "headers": [
        {
          "level": 3,
          "title": "目录",
          "slug": "目录"
        }
      ]
    },
    {
      "title": "渲染树的形成原理",
      "frontmatter": {
        "title": "渲染树的形成原理",
        "date": "2019-10-28T00:00:00.000Z",
        "tags": [
          "CSS",
          "渲染树",
          "浏览器"
        ]
      },
      "regularPath": "/brower/renderTree.html",
      "relativePath": "brower/renderTree.md",
      "key": "v-1c79b5f9",
      "path": "/brower/renderTree.html",
      "headers": [
        {
          "level": 2,
          "title": "什么是DOM",
          "slug": "什么是dom"
        },
        {
          "level": 2,
          "title": "渲染树最终形成经历了哪些",
          "slug": "渲染树最终形成经历了哪些"
        },
        {
          "level": 2,
          "title": "HTML解析器",
          "slug": "html解析器"
        },
        {
          "level": 2,
          "title": "CSS解析器",
          "slug": "css解析器"
        },
        {
          "level": 2,
          "title": "javascript对DOM树与CSSOM树创建的影响",
          "slug": "javascript对dom树与cssom树创建的影响"
        },
        {
          "level": 2,
          "title": "构建渲染树",
          "slug": "构建渲染树"
        },
        {
          "level": 2,
          "title": "本文渲染树形成过程可以做哪些优化",
          "slug": "本文渲染树形成过程可以做哪些优化"
        },
        {
          "level": 2,
          "title": "总结",
          "slug": "总结"
        },
        {
          "level": 3,
          "title": "参考资料:",
          "slug": "参考资料"
        },
        {
          "level": 3,
          "title": "关注我",
          "slug": "关注我"
        }
      ]
    },
    {
      "title": "SQL 和 NoSQL 的区别与选择",
      "frontmatter": {
        "title": "SQL 和 NoSQL 的区别与选择",
        "date": "2019-05-28T00:00:00.000Z",
        "tags": [
          "数据库"
        ]
      },
      "regularPath": "/database/choice.html",
      "relativePath": "database/choice.md",
      "key": "v-034e5059",
      "path": "/database/choice.html",
      "headers": [
        {
          "level": 2,
          "title": "概念",
          "slug": "概念"
        },
        {
          "level": 3,
          "title": "关系型数据库",
          "slug": "关系型数据库"
        },
        {
          "level": 3,
          "title": "非关系型数据库",
          "slug": "非关系型数据库"
        },
        {
          "level": 2,
          "title": "二者对比",
          "slug": "二者对比"
        },
        {
          "level": 3,
          "title": "存储方式：",
          "slug": "存储方式"
        },
        {
          "level": 3,
          "title": "表/数据集合的数据的关系",
          "slug": "表-数据集合的数据的关系"
        },
        {
          "level": 3,
          "title": "外部数据存储",
          "slug": "外部数据存储"
        },
        {
          "level": 3,
          "title": "SQL中的JOIN查询",
          "slug": "sql中的join查询"
        },
        {
          "level": 3,
          "title": "数据耦合性",
          "slug": "数据耦合性"
        },
        {
          "level": 3,
          "title": "事务",
          "slug": "事务"
        },
        {
          "level": 3,
          "title": "增删改查语法",
          "slug": "增删改查语法"
        },
        {
          "level": 3,
          "title": "数据完整性",
          "slug": "数据完整性"
        },
        {
          "level": 3,
          "title": "查询性能",
          "slug": "查询性能"
        },
        {
          "level": 2,
          "title": "如何选择",
          "slug": "如何选择"
        },
        {
          "level": 3,
          "title": "适合使用SQL开发的项目：",
          "slug": "适合使用sql开发的项目"
        },
        {
          "level": 3,
          "title": "适合使用NoSQL开发的项目：",
          "slug": "适合使用nosql开发的项目"
        },
        {
          "level": 2,
          "title": "读完本文后的思考",
          "slug": "读完本文后的思考"
        }
      ]
    },
    {
      "title": "Redis详细学习 入门篇",
      "frontmatter": {
        "title": "Redis详细学习 入门篇",
        "date": "2019-05-07T00:00:00.000Z",
        "tags": [
          "Redis"
        ]
      },
      "regularPath": "/database/detail-redis1.html",
      "relativePath": "database/detail-redis1.md",
      "key": "v-2dbc8d2e",
      "path": "/database/detail-redis1.html",
      "headers": [
        {
          "level": 2,
          "title": "什么是Redis",
          "slug": "什么是redis"
        },
        {
          "level": 2,
          "title": "redis的应用场景",
          "slug": "redis的应用场景"
        },
        {
          "level": 2,
          "title": "redis安装与启动",
          "slug": "redis安装与启动"
        },
        {
          "level": 2,
          "title": "redis的基本数据类型",
          "slug": "redis的基本数据类型"
        }
      ]
    },
    {
      "title": "Redis详细学习 进阶篇",
      "frontmatter": {
        "title": "Redis详细学习 进阶篇",
        "date": "2019-05-09T00:00:00.000Z",
        "tags": [
          "Redis"
        ]
      },
      "regularPath": "/database/detail-redis2.html",
      "relativePath": "database/detail-redis2.md",
      "key": "v-7306d1e7",
      "path": "/database/detail-redis2.html",
      "headers": [
        {
          "level": 2,
          "title": "redis多数据库",
          "slug": "redis多数据库"
        },
        {
          "level": 2,
          "title": "redis事务的概念",
          "slug": "redis事务的概念"
        },
        {
          "level": 2,
          "title": "redis数据持久化",
          "slug": "redis数据持久化"
        }
      ]
    },
    {
      "title": "Redis详细学习 实战篇",
      "frontmatter": {
        "title": "Redis详细学习 实战篇",
        "date": "2019-05-11T00:00:00.000Z",
        "tags": [
          "Redis"
        ]
      },
      "regularPath": "/database/detail-redis3.html",
      "relativePath": "database/detail-redis3.md",
      "key": "v-06282b36",
      "path": "/database/detail-redis3.html",
      "headers": [
        {
          "level": 2,
          "title": "前言:",
          "slug": "前言"
        },
        {
          "level": 2,
          "title": "应用场景",
          "slug": "应用场景"
        }
      ]
    },
    {
      "title": "MySQL 基础架构你不知道的那些事！",
      "frontmatter": {
        "title": "MySQL 基础架构你不知道的那些事！",
        "date": "2019-05-12T00:00:00.000Z",
        "tags": [
          "MySQL"
        ]
      },
      "regularPath": "/database/mysql/baseFrame.html",
      "relativePath": "database/mysql/baseFrame.md",
      "key": "v-cacbb322",
      "path": "/database/mysql/baseFrame.html",
      "headers": [
        {
          "level": 2,
          "title": "提出问题：",
          "slug": "提出问题"
        },
        {
          "level": 2,
          "title": "mysql的基础架构",
          "slug": "mysql的基础架构"
        },
        {
          "level": 2,
          "title": "Mysql基本架构示意图",
          "slug": "mysql基本架构示意图"
        },
        {
          "level": 2,
          "title": "连接器",
          "slug": "连接器"
        },
        {
          "level": 2,
          "title": "查询缓存",
          "slug": "查询缓存"
        },
        {
          "level": 2,
          "title": "分析器",
          "slug": "分析器"
        },
        {
          "level": 2,
          "title": "优化器",
          "slug": "优化器"
        },
        {
          "level": 2,
          "title": "执行器",
          "slug": "执行器"
        },
        {
          "level": 2,
          "title": "存储引擎",
          "slug": "存储引擎"
        },
        {
          "level": 2,
          "title": "总结",
          "slug": "总结"
        }
      ]
    },
    {
      "title": "删库跑路后真的没有办法弥补了吗？！",
      "frontmatter": {
        "title": "删库跑路后真的没有办法弥补了吗？！",
        "date": "2019-05-16T00:00:00.000Z",
        "tags": [
          "数据库",
          "日志系统"
        ]
      },
      "regularPath": "/database/mysql/logSystem.html",
      "relativePath": "database/mysql/logSystem.md",
      "key": "v-e7493e7e",
      "path": "/database/mysql/logSystem.html",
      "headers": [
        {
          "level": 2,
          "title": "redo日志(重做日志)",
          "slug": "redo日志-重做日志"
        },
        {
          "level": 3,
          "title": "redo中的环状结构",
          "slug": "redo中的环状结构"
        },
        {
          "level": 3,
          "title": "redo日志作用(回答提出问题1)",
          "slug": "redo日志作用-回答提出问题1"
        },
        {
          "level": 2,
          "title": "binlog日志(归档日志)",
          "slug": "binlog日志-归档日志"
        },
        {
          "level": 3,
          "title": "binlog日志作用(回答提出问题2)",
          "slug": "binlog日志作用-回答提出问题2"
        },
        {
          "level": 2,
          "title": "redo日志与binlog日志对比",
          "slug": "redo日志与binlog日志对比"
        },
        {
          "level": 3,
          "title": "更新语句执行流程(与日志关系)",
          "slug": "更新语句执行流程-与日志关系"
        },
        {
          "level": 2,
          "title": "开发过程中如何为mysql设置这两种保存日志的配置",
          "slug": "开发过程中如何为mysql设置这两种保存日志的配置"
        },
        {
          "level": 2,
          "title": "如何查看这两种日志",
          "slug": "如何查看这两种日志"
        },
        {
          "level": 3,
          "title": "关于日志系统的一些误区和疑问",
          "slug": "关于日志系统的一些误区和疑问"
        },
        {
          "level": 2,
          "title": "总结与宣传",
          "slug": "总结与宣传"
        }
      ]
    },
    {
      "title": "常用的数据库语句",
      "frontmatter": {
        "title": "常用的数据库语句",
        "date": "2019-05-18T00:00:00.000Z",
        "tags": [
          "数据库"
        ]
      },
      "regularPath": "/database/mysql/optimize.html",
      "relativePath": "database/mysql/optimize.md",
      "key": "v-799c6ef9",
      "path": "/database/mysql/optimize.html",
      "headers": [
        {
          "level": 2,
          "title": "直接看语句",
          "slug": "直接看语句"
        },
        {
          "level": 2,
          "title": "DATE_FORMAT函数说明",
          "slug": "date-format函数说明"
        },
        {
          "level": 2,
          "title": "> 需求2: 查询结果单位换算后保留两位小数",
          "slug": "需求2-查询结果单位换算后保留两位小数"
        }
      ]
    },
    {
      "title": "如何写优雅的SQL原生语句？",
      "frontmatter": {
        "title": "如何写优雅的SQL原生语句？",
        "date": "2019-05-26T00:00:00.000Z",
        "tags": [
          "数据库"
        ]
      },
      "regularPath": "/database/mysql/writeSql.html",
      "relativePath": "database/mysql/writeSql.md",
      "key": "v-7d917239",
      "path": "/database/mysql/writeSql.html",
      "headers": [
        {
          "level": 2,
          "title": "前言：",
          "slug": "前言"
        },
        {
          "level": 2,
          "title": "语句中各子句完整执行顺序概括（按照顺序号执行）",
          "slug": "语句中各子句完整执行顺序概括-按照顺序号执行"
        },
        {
          "level": 3,
          "title": "每个子句执行顺序分析",
          "slug": "每个子句执行顺序分析"
        },
        {
          "level": 2,
          "title": "开发某需求写的一段sql",
          "slug": "开发某需求写的一段sql"
        },
        {
          "level": 2,
          "title": "sql语句中的别名",
          "slug": "sql语句中的别名"
        },
        {
          "level": 2,
          "title": "书写sql语句的注意事项",
          "slug": "书写sql语句的注意事项"
        }
      ]
    },
    {
      "title": "数据库必知必会系列",
      "frontmatter": {},
      "regularPath": "/database/",
      "relativePath": "database/readme.md",
      "key": "v-0995f732",
      "path": "/database/",
      "headers": [
        {
          "level": 2,
          "title": "数据库必知必会系列",
          "slug": "数据库必知必会系列"
        }
      ]
    },
    {
      "title": "js高频面试题",
      "frontmatter": {
        "title": "js高频面试题",
        "date": "2019-05-25T00:00:00.000Z",
        "tags": [
          "Javascript",
          "面试"
        ]
      },
      "regularPath": "/interview/js10.html",
      "relativePath": "interview/js10.md",
      "key": "v-4672ab0e",
      "path": "/interview/js10.html",
      "headers": [
        {
          "level": 2,
          "title": "1.说说你对闭包的认识",
          "slug": "_1-说说你对闭包的认识"
        },
        {
          "level": 3,
          "title": "什么是闭包",
          "slug": "什么是闭包"
        },
        {
          "level": 3,
          "title": "闭包解决了什么问题",
          "slug": "闭包解决了什么问题"
        },
        {
          "level": 3,
          "title": "闭包的应用场景",
          "slug": "闭包的应用场景"
        },
        {
          "level": 3,
          "title": "闭包的缺点",
          "slug": "闭包的缺点"
        },
        {
          "level": 2,
          "title": "2. 跨域问题有哪些处理方式",
          "slug": "_2-跨域问题有哪些处理方式"
        },
        {
          "level": 3,
          "title": "跨域解决方案",
          "slug": "跨域解决方案"
        },
        {
          "level": 3,
          "title": "Ⅰ.通过jsonp跨域",
          "slug": "i-通过jsonp跨域"
        },
        {
          "level": 3,
          "title": "Ⅱ.跨域资源共享（CORS）",
          "slug": "ii-跨域资源共享-cors"
        },
        {
          "level": 3,
          "title": "Ⅲ.nodejs中间件代理跨域",
          "slug": "iii-nodejs中间件代理跨域"
        },
        {
          "level": 3,
          "title": "Ⅳ.nginx反向代理中设置",
          "slug": "iv-nginx反向代理中设置"
        },
        {
          "level": 2,
          "title": "3. for...in 和 for...of的区别",
          "slug": "_3-for-in-和-for-of的区别"
        },
        {
          "level": 2,
          "title": "4. new一个对象, 这个过程中发生了什么",
          "slug": "_4-new一个对象-这个过程中发生了什么"
        },
        {
          "level": 2,
          "title": "5. js的防抖和节流是什么",
          "slug": "_5-js的防抖和节流是什么"
        },
        {
          "level": 2,
          "title": "6. 数组中常用的方法有哪些",
          "slug": "_6-数组中常用的方法有哪些"
        },
        {
          "level": 2,
          "title": "7. 怎么判断一个object是否是数组",
          "slug": "_7-怎么判断一个object是否是数组"
        },
        {
          "level": 2,
          "title": "8. 继承有哪些方式",
          "slug": "_8-继承有哪些方式"
        },
        {
          "level": 2,
          "title": "9. 说说js中call,apply,bind之间的关系",
          "slug": "_9-说说js中call-apply-bind之间的关系"
        },
        {
          "level": 3,
          "title": "apply 和 call",
          "slug": "apply-和-call"
        },
        {
          "level": 3,
          "title": "bind 与 apply、call区别",
          "slug": "bind-与-apply、call区别"
        },
        {
          "level": 3,
          "title": "bind,apply,call的共同和不同点：",
          "slug": "bind-apply-call的共同和不同点"
        },
        {
          "level": 2,
          "title": "10. Promise",
          "slug": "_10-promise"
        },
        {
          "level": 3,
          "title": "1. 了解Promise吗?",
          "slug": "_1-了解promise吗"
        },
        {
          "level": 3,
          "title": "2.Promise 解决了什么问题?",
          "slug": "_2-promise-解决了什么问题"
        },
        {
          "level": 3,
          "title": "3. Promise 如何使用?",
          "slug": "_3-promise-如何使用"
        },
        {
          "level": 3,
          "title": "4. Promise 常用的方法有哪些？它们的作用是什么？",
          "slug": "_4-promise-常用的方法有哪些-它们的作用是什么"
        },
        {
          "level": 3,
          "title": "5. Promise 在事件循环中的执行过程是怎样的",
          "slug": "_5-promise-在事件循环中的执行过程是怎样的"
        },
        {
          "level": 2,
          "title": "总结",
          "slug": "总结"
        }
      ]
    },
    {
      "title": "前端面试 10个css高频面试题",
      "frontmatter": {
        "title": "前端面试 10个css高频面试题",
        "date": "2019-05-19T00:00:00.000Z",
        "tags": [
          "CSS",
          "面试"
        ]
      },
      "regularPath": "/interview/css.html",
      "relativePath": "interview/css.md",
      "key": "v-370b7719",
      "path": "/interview/css.html",
      "headers": [
        {
          "level": 2,
          "title": "1. BFC机制",
          "slug": "_1-bfc机制"
        },
        {
          "level": 2,
          "title": "2. CSS3中新增的选择器以及属性",
          "slug": "_2-css3中新增的选择器以及属性"
        },
        {
          "level": 2,
          "title": "3. 居中布局",
          "slug": "_3-居中布局"
        },
        {
          "level": 2,
          "title": "4. 清除浮动有哪些方法, 各有什么优缺点",
          "slug": "_4-清除浮动有哪些方法-各有什么优缺点"
        },
        {
          "level": 2,
          "title": "5. 用纯CSS创建一个三角形的原理是什么",
          "slug": "_5-用纯css创建一个三角形的原理是什么"
        },
        {
          "level": 2,
          "title": "6. 实现三栏布局有哪些方法, 分别描述一下",
          "slug": "_6-实现三栏布局有哪些方法-分别描述一下"
        },
        {
          "level": 2,
          "title": "7. css3实现0.5px的细线",
          "slug": "_7-css3实现0-5px的细线"
        },
        {
          "level": 2,
          "title": "8. link 与 @import 的区别",
          "slug": "_8-link-与-import-的区别"
        },
        {
          "level": 2,
          "title": "9. 开发中为什么要初始化css样式",
          "slug": "_9-开发中为什么要初始化css样式"
        },
        {
          "level": 2,
          "title": "10. CSS优化、提高性能的方法有哪些",
          "slug": "_10-css优化、提高性能的方法有哪些"
        }
      ]
    },
    {
      "title": "面试注意事项",
      "frontmatter": {
        "title": "面试注意事项",
        "date": "2019-05-27T00:00:00.000Z",
        "tags": [
          "面试"
        ]
      },
      "regularPath": "/interview/notes.html",
      "relativePath": "interview/notes.md",
      "key": "v-21d68519",
      "path": "/interview/notes.html",
      "headers": [
        {
          "level": 2,
          "title": "带上个人简历",
          "slug": "带上个人简历"
        },
        {
          "level": 2,
          "title": "面试官是个怎样的人",
          "slug": "面试官是个怎样的人"
        },
        {
          "level": 2,
          "title": "你有什么想问的？",
          "slug": "你有什么想问的"
        },
        {
          "level": 2,
          "title": "不要被期权、股权诱惑",
          "slug": "不要被期权、股权诱惑"
        },
        {
          "level": 2,
          "title": "公积金和社保给怎么交",
          "slug": "公积金和社保给怎么交"
        },
        {
          "level": 2,
          "title": "不尊重你和你的财产的公司",
          "slug": "不尊重你和你的财产的公司"
        },
        {
          "level": 2,
          "title": "多了解下公司文化",
          "slug": "多了解下公司文化"
        },
        {
          "level": 2,
          "title": "尽量去大厂，尽量不要去外包公司",
          "slug": "尽量去大厂-尽量不要去外包公司"
        }
      ]
    },
    {
      "title": "面试",
      "frontmatter": {},
      "regularPath": "/interview/",
      "relativePath": "interview/readme.md",
      "key": "v-015b2d3e",
      "path": "/interview/",
      "headers": [
        {
          "level": 3,
          "title": "vue相关",
          "slug": "vue相关"
        },
        {
          "level": 3,
          "title": "javascript",
          "slug": "javascript"
        },
        {
          "level": 3,
          "title": "css",
          "slug": "css"
        }
      ]
    },
    {
      "title": "面试之手写代码",
      "frontmatter": {
        "title": "面试之手写代码",
        "date": "2020-01-23T00:00:00.000Z",
        "tags": [
          "Javascript",
          "面试"
        ]
      },
      "regularPath": "/interview/rewriteJs.html",
      "relativePath": "interview/rewriteJs.md",
      "key": "v-36d5d319",
      "path": "/interview/rewriteJs.html",
      "headers": [
        {
          "level": 2,
          "title": "模仿实现new创建对象",
          "slug": "模仿实现new创建对象"
        },
        {
          "level": 2,
          "title": "模仿实现instanceof",
          "slug": "模仿实现instanceof"
        },
        {
          "level": 2,
          "title": "模仿实现call",
          "slug": "模仿实现call"
        },
        {
          "level": 2,
          "title": "模仿实现apply",
          "slug": "模仿实现apply"
        },
        {
          "level": 2,
          "title": "模仿实现bind",
          "slug": "模仿实现bind"
        }
      ]
    },
    {
      "title": "js数组去重 面试如何回答",
      "frontmatter": {
        "title": "js数组去重 面试如何回答",
        "date": "2019-12-26T00:00:00.000Z",
        "tags": [
          "Javascript",
          "面试"
        ]
      },
      "regularPath": "/interview/unique.html",
      "relativePath": "interview/unique.md",
      "key": "v-5e249ae7",
      "path": "/interview/unique.html",
      "headers": [
        {
          "level": 2,
          "title": "为什么写这篇文章？",
          "slug": "为什么写这篇文章"
        },
        {
          "level": 2,
          "title": "当面试官问到时怎么回答？",
          "slug": "当面试官问到时怎么回答"
        },
        {
          "level": 3,
          "title": "首先:我知道多少种去重方式",
          "slug": "首先-我知道多少种去重方式"
        },
        {
          "level": 3,
          "title": "然后:询问面试官具体场景",
          "slug": "然后-询问面试官具体场景"
        },
        {
          "level": 3,
          "title": "性能考虑(是想要最快的速度查到数据吗？)",
          "slug": "性能考虑-是想要最快的速度查到数据吗"
        },
        {
          "level": 3,
          "title": "兼容性与场景考虑(数组中是否包含对象，NaN等？)",
          "slug": "兼容性与场景考虑-数组中是否包含对象-nan等"
        },
        {
          "level": 3,
          "title": "内存考虑(去重复过程中，是想要空间复杂度最低吗？)",
          "slug": "内存考虑-去重复过程中-是想要空间复杂度最低吗"
        },
        {
          "level": 2,
          "title": "补充说明第三方库lodash",
          "slug": "补充说明第三方库lodash"
        },
        {
          "level": 3,
          "title": "lodash 如何实现去重",
          "slug": "lodash-如何实现去重"
        },
        {
          "level": 2,
          "title": "总结",
          "slug": "总结"
        },
        {
          "level": 2,
          "title": "参考文章",
          "slug": "参考文章"
        },
        {
          "level": 3,
          "title": "关注我",
          "slug": "关注我"
        },
        {
          "level": 3,
          "title": "Node系列原创文章",
          "slug": "node系列原创文章"
        }
      ]
    },
    {
      "title": "vue常考面试题",
      "frontmatter": {
        "title": "vue常考面试题",
        "date": "2019-06-28T00:00:00.000Z",
        "tags": [
          "Vue",
          "面试"
        ]
      },
      "regularPath": "/interview/vue.html",
      "relativePath": "interview/vue.md",
      "key": "v-10e6468e",
      "path": "/interview/vue.html",
      "headers": [
        {
          "level": 2,
          "title": "快速导航",
          "slug": "快速导航"
        },
        {
          "level": 2,
          "title": "对于MVVM的理解",
          "slug": "对于mvvm的理解"
        },
        {
          "level": 2,
          "title": "开发中常用的指令有哪些",
          "slug": "开发中常用的指令有哪些"
        },
        {
          "level": 2,
          "title": "请详细说下你对vue生命周期的理解",
          "slug": "请详细说下你对vue生命周期的理解"
        },
        {
          "level": 2,
          "title": "Vue的双向数据绑定原理是什么",
          "slug": "vue的双向数据绑定原理是什么"
        },
        {
          "level": 2,
          "title": "Proxy相比于defineProperty的优势",
          "slug": "proxy相比于defineproperty的优势"
        },
        {
          "level": 2,
          "title": "vue-router有哪几种导航守卫",
          "slug": "vue-router有哪几种导航守卫"
        },
        {
          "level": 3,
          "title": "1.全局守卫",
          "slug": "_1-全局守卫"
        },
        {
          "level": 3,
          "title": "2.路由独享守卫",
          "slug": "_2-路由独享守卫"
        },
        {
          "level": 3,
          "title": "3.路由组件内的守卫",
          "slug": "_3-路由组件内的守卫"
        },
        {
          "level": 2,
          "title": "Vue的路由实现:hash模式和history模式",
          "slug": "vue的路由实现-hash模式和history模式"
        },
        {
          "level": 3,
          "title": "hash模式：",
          "slug": "hash模式"
        },
        {
          "level": 3,
          "title": "history模式：",
          "slug": "history模式"
        },
        {
          "level": 2,
          "title": "组件之间的传值通信",
          "slug": "组件之间的传值通信"
        },
        {
          "level": 3,
          "title": "3.非父子,兄弟组件之间通信",
          "slug": "_3-非父子-兄弟组件之间通信"
        },
        {
          "level": 2,
          "title": "Vue与Angular以及React的区别？",
          "slug": "vue与angular以及react的区别"
        },
        {
          "level": 2,
          "title": "vuex是什么？怎么使用？哪种功能场景使用它？",
          "slug": "vuex是什么-怎么使用-哪种功能场景使用它"
        },
        {
          "level": 3,
          "title": "公众号技术栈路线",
          "slug": "公众号技术栈路线"
        },
        {
          "level": 3,
          "title": "加入我们",
          "slug": "加入我们"
        }
      ]
    },
    {
      "title": "node必知必会系列",
      "frontmatter": {},
      "regularPath": "/node-zy/",
      "relativePath": "node-zy/README.md",
      "key": "v-0f85b128",
      "path": "/node-zy/",
      "headers": [
        {
          "level": 2,
          "title": "node必知必会系列",
          "slug": "node必知必会系列"
        },
        {
          "level": 2,
          "title": "交流群里讨论问题整理",
          "slug": "交流群里讨论问题整理"
        }
      ]
    },
    {
      "title": "node核心模块 -文件路径path",
      "frontmatter": {
        "title": "node核心模块 -文件路径path",
        "date": "2019-07-30T00:00:00.000Z",
        "tags": [
          "Node.js"
        ]
      },
      "regularPath": "/node-zy/path.html",
      "relativePath": "node-zy/path.md",
      "key": "v-079e2011",
      "path": "/node-zy/path.html",
      "headers": [
        {
          "level": 2,
          "title": "path",
          "slug": "path"
        },
        {
          "level": 3,
          "title": "path.normalize",
          "slug": "path-normalize"
        },
        {
          "level": 3,
          "title": "path.join",
          "slug": "path-join"
        },
        {
          "level": 3,
          "title": "path.parse",
          "slug": "path-parse"
        },
        {
          "level": 3,
          "title": "path.basename",
          "slug": "path-basename"
        },
        {
          "level": 3,
          "title": "path.dirname",
          "slug": "path-dirname"
        },
        {
          "level": 3,
          "title": "path.extname",
          "slug": "path-extname"
        },
        {
          "level": 3,
          "title": "path.resolve",
          "slug": "path-resolve"
        },
        {
          "level": 3,
          "title": "path.relative",
          "slug": "path-relative"
        },
        {
          "level": 2,
          "title": "总结",
          "slug": "总结"
        }
      ]
    },
    {
      "title": "Node.js中stream模块详解",
      "frontmatter": {
        "title": "Node.js中stream模块详解",
        "date": "2019-06-14T00:00:00.000Z",
        "tags": [
          "Node.js"
        ]
      },
      "regularPath": "/node-zy/stream.html",
      "relativePath": "node-zy/stream.md",
      "key": "v-df6e1f4a",
      "path": "/node-zy/stream.html",
      "headers": [
        {
          "level": 3,
          "title": "stream定义",
          "slug": "stream定义"
        },
        {
          "level": 2,
          "title": "为什么要学习stream",
          "slug": "为什么要学习stream"
        },
        {
          "level": 3,
          "title": "视频播放例子",
          "slug": "视频播放例子"
        },
        {
          "level": 3,
          "title": "读取大文件data的例子",
          "slug": "读取大文件data的例子"
        },
        {
          "level": 2,
          "title": "stream流转过程",
          "slug": "stream流转过程"
        },
        {
          "level": 3,
          "title": "stream从哪里来-soucre",
          "slug": "stream从哪里来-soucre"
        },
        {
          "level": 3,
          "title": "连接水桶的管道-pipe",
          "slug": "连接水桶的管道-pipe"
        },
        {
          "level": 3,
          "title": "stream到哪里去-dest",
          "slug": "stream到哪里去-dest"
        },
        {
          "level": 2,
          "title": "stream应用场景",
          "slug": "stream应用场景"
        },
        {
          "level": 3,
          "title": "介绍一个压力测试的小工具",
          "slug": "介绍一个压力测试的小工具"
        },
        {
          "level": 3,
          "title": "get请求中应用stream",
          "slug": "get请求中应用stream"
        },
        {
          "level": 3,
          "title": "post中使用stream",
          "slug": "post中使用stream"
        },
        {
          "level": 3,
          "title": "post与get使用stream总结",
          "slug": "post与get使用stream总结"
        },
        {
          "level": 3,
          "title": "在文件操作中使用stream",
          "slug": "在文件操作中使用stream"
        },
        {
          "level": 3,
          "title": "前端一些打包工具的底层实现",
          "slug": "前端一些打包工具的底层实现"
        },
        {
          "level": 2,
          "title": "stream的种类",
          "slug": "stream的种类"
        },
        {
          "level": 2,
          "title": "stream有什么弊端",
          "slug": "stream有什么弊端"
        },
        {
          "level": 2,
          "title": "stream的常见类库",
          "slug": "stream的常见类库"
        },
        {
          "level": 2,
          "title": "总结",
          "slug": "总结"
        }
      ]
    },
    {
      "title": "使用 Node.js 搭建一个 API 网关(助力微服务)",
      "frontmatter": {
        "title": "使用 Node.js 搭建一个 API 网关(助力微服务)",
        "date": "2020-04-08T00:00:00.000Z",
        "tags": [
          "Node.js",
          "API 网关"
        ]
      },
      "regularPath": "/node/APIGateway.html",
      "relativePath": "node/APIGateway.md",
      "key": "v-3a513799",
      "path": "/node/APIGateway.html",
      "headers": [
        {
          "level": 2,
          "title": "微服务和消费者",
          "slug": "微服务和消费者"
        },
        {
          "level": 2,
          "title": "什么是 API 网关？",
          "slug": "什么是-api-网关"
        },
        {
          "level": 3,
          "title": "Node.js 用于前端团队的 API 网关",
          "slug": "node-js-用于前端团队的-api-网关"
        },
        {
          "level": 2,
          "title": "API 网关功能",
          "slug": "api-网关功能"
        },
        {
          "level": 3,
          "title": "路由和版本控制",
          "slug": "路由和版本控制"
        },
        {
          "level": 3,
          "title": "网关设计的进化",
          "slug": "网关设计的进化"
        },
        {
          "level": 3,
          "title": "认证方式",
          "slug": "认证方式"
        },
        {
          "level": 3,
          "title": "数据汇总",
          "slug": "数据汇总"
        },
        {
          "level": 3,
          "title": "序列化格式转换",
          "slug": "序列化格式转换"
        },
        {
          "level": 3,
          "title": "协议转换",
          "slug": "协议转换"
        },
        {
          "level": 3,
          "title": "限速和缓存",
          "slug": "限速和缓存"
        },
        {
          "level": 3,
          "title": "超负荷的 API 网关",
          "slug": "超负荷的-api-网关"
        },
        {
          "level": 2,
          "title": "Node.js API 网关",
          "slug": "node-js-api-网关"
        },
        {
          "level": 3,
          "title": "Node.js API 网关总结",
          "slug": "node-js-api-网关总结"
        }
      ]
    },
    {
      "title": "Node 与底层之间如何执行异步 I/O 调用",
      "frontmatter": {
        "title": "Node 与底层之间如何执行异步 I/O 调用",
        "date": "2020-01-09T00:00:00.000Z",
        "tags": [
          "Node.js",
          "异步I/O"
        ]
      },
      "regularPath": "/node/AsyncIO.html",
      "relativePath": "node/AsyncIO.md",
      "key": "v-2318913b",
      "path": "/node/AsyncIO.html",
      "headers": [
        {
          "level": 2,
          "title": "理解本文先要学习的几个概念",
          "slug": "理解本文先要学习的几个概念"
        },
        {
          "level": 3,
          "title": "Node.js 模块分类",
          "slug": "node-js-模块分类"
        },
        {
          "level": 3,
          "title": "libuv",
          "slug": "libuv"
        },
        {
          "level": 3,
          "title": "IOCP",
          "slug": "iocp"
        },
        {
          "level": 3,
          "title": "线程池",
          "slug": "线程池"
        },
        {
          "level": 2,
          "title": "Node 与底层之间的异步I/O调用流程",
          "slug": "node-与底层之间的异步i-o调用流程"
        },
        {
          "level": 3,
          "title": "事件循环",
          "slug": "事件循环"
        },
        {
          "level": 3,
          "title": "底层调用与事件产生",
          "slug": "底层调用与事件产生"
        },
        {
          "level": 2,
          "title": "异步 I/O 助力 Node.js 高性能",
          "slug": "异步-i-o-助力-node-js-高性能"
        },
        {
          "level": 3,
          "title": "关注我",
          "slug": "关注我"
        },
        {
          "level": 2,
          "title": "参考",
          "slug": "参考"
        }
      ]
    },
    {
      "title": "node必知必会系列",
      "frontmatter": {},
      "regularPath": "/node/",
      "relativePath": "node/README.md",
      "key": "v-70c26a12",
      "path": "/node/",
      "headers": [
        {
          "level": 2,
          "title": "node必知必会系列",
          "slug": "node必知必会系列"
        },
        {
          "level": 2,
          "title": "交流群里讨论问题整理",
          "slug": "交流群里讨论问题整理"
        }
      ]
    },
    {
      "title": "Node.js核心模块-buffer",
      "frontmatter": {
        "title": "Node.js核心模块-buffer",
        "date": "2019-06-09T00:00:00.000Z",
        "tags": [
          "Node.js"
        ]
      },
      "regularPath": "/node/buffer.html",
      "relativePath": "node/buffer.md",
      "key": "v-87f4d64e",
      "path": "/node/buffer.html",
      "headers": [
        {
          "level": 2,
          "title": "Buffer探究",
          "slug": "buffer探究"
        },
        {
          "level": 2,
          "title": "什么是二进制",
          "slug": "什么是二进制"
        },
        {
          "level": 2,
          "title": "node中为什么会出现Buffer这个模块",
          "slug": "node中为什么会出现buffer这个模块"
        },
        {
          "level": 2,
          "title": "Buffer创建",
          "slug": "buffer创建"
        },
        {
          "level": 2,
          "title": "Buffer的内存分配机制",
          "slug": "buffer的内存分配机制"
        },
        {
          "level": 2,
          "title": "Buffer与stream",
          "slug": "buffer与stream"
        },
        {
          "level": 3,
          "title": "关注我",
          "slug": "关注我"
        }
      ]
    },
    {
      "title": "node.js十个常见误区",
      "frontmatter": {
        "title": "node.js十个常见误区",
        "date": "2019-08-26T00:00:00.000Z",
        "tags": [
          "Node.js"
        ]
      },
      "regularPath": "/node/errors.html",
      "relativePath": "node/errors.md",
      "key": "v-a0e6d78e",
      "path": "/node/errors.html",
      "headers": [
        {
          "level": 2,
          "title": "错误1：阻塞事件循环",
          "slug": "错误1-阻塞事件循环"
        },
        {
          "level": 2,
          "title": "错误2：多次调用一个回调函数",
          "slug": "错误2-多次调用一个回调函数"
        },
        {
          "level": 2,
          "title": "错误3：深层嵌套的回调函数",
          "slug": "错误3-深层嵌套的回调函数"
        },
        {
          "level": 2,
          "title": "错误4：期待回调函数同步执行",
          "slug": "错误4-期待回调函数同步执行"
        },
        {
          "level": 2,
          "title": "错误5：给“exports” 赋值，而不是“module.exports”",
          "slug": "错误5-给-exports-赋值-而不是-module-exports"
        },
        {
          "level": 2,
          "title": "错误6：从回调里抛出错误",
          "slug": "错误6-从回调里抛出错误"
        },
        {
          "level": 2,
          "title": "错误7：认为 Number 是一种整型数据格式",
          "slug": "错误7-认为-number-是一种整型数据格式"
        },
        {
          "level": 2,
          "title": "错误8：忽略了流式 API 的优势",
          "slug": "错误8-忽略了流式-api-的优势"
        },
        {
          "level": 2,
          "title": "错误9：出于 Debug 的目的使用 Console.log",
          "slug": "错误9-出于-debug-的目的使用-console-log"
        },
        {
          "level": 2,
          "title": "错误10：不使用监控程序",
          "slug": "错误10-不使用监控程序"
        },
        {
          "level": 2,
          "title": "总结",
          "slug": "总结"
        }
      ]
    },
    {
      "title": "node事件循环",
      "frontmatter": {
        "title": "node事件循环",
        "tags": [
          "Node.js"
        ]
      },
      "regularPath": "/node/event_loop.html",
      "relativePath": "node/event_loop.md",
      "key": "v-dd448c0e",
      "path": "/node/event_loop.html",
      "headers": [
        {
          "level": 2,
          "title": "面试题",
          "slug": "面试题"
        },
        {
          "level": 2,
          "title": "提出问题",
          "slug": "提出问题"
        },
        {
          "level": 2,
          "title": "详细讲解",
          "slug": "详细讲解"
        },
        {
          "level": 2,
          "title": "整体结论",
          "slug": "整体结论"
        },
        {
          "level": 2,
          "title": "附件:参考资料",
          "slug": "附件-参考资料"
        }
      ]
    },
    {
      "title": "源码解读,一文彻底搞懂Events模块",
      "frontmatter": {
        "title": "源码解读,一文彻底搞懂Events模块",
        "date": "2019-09-05T00:00:00.000Z",
        "tags": [
          "Node.js",
          "Events"
        ]
      },
      "regularPath": "/node/events.html",
      "relativePath": "node/events.md",
      "key": "v-02aacdf9",
      "path": "/node/events.html",
      "headers": [
        {
          "level": 2,
          "title": "面试会问",
          "slug": "面试会问"
        },
        {
          "level": 2,
          "title": "发布/订阅者模式",
          "slug": "发布-订阅者模式"
        },
        {
          "level": 3,
          "title": "生活中的发布/订阅者模式",
          "slug": "生活中的发布-订阅者模式"
        },
        {
          "level": 3,
          "title": "实例的代码实现与分析",
          "slug": "实例的代码实现与分析"
        },
        {
          "level": 3,
          "title": "发布/订阅者模式的优缺点",
          "slug": "发布-订阅者模式的优缺点"
        },
        {
          "level": 2,
          "title": "EventEmitter 与 发布/订阅模式的关系",
          "slug": "eventemitter-与-发布-订阅模式的关系"
        },
        {
          "level": 3,
          "title": "事件的基本组成要素",
          "slug": "事件的基本组成要素"
        },
        {
          "level": 3,
          "title": "EventEmitter 定义",
          "slug": "eventemitter-定义"
        },
        {
          "level": 3,
          "title": "EventEs 的一些常用官方API源码与发布/订阅模式对比学习",
          "slug": "eventes-的一些常用官方api源码与发布-订阅模式对比学习"
        },
        {
          "level": 2,
          "title": "阅读源码后一些疑问的解释",
          "slug": "阅读源码后一些疑问的解释"
        },
        {
          "level": 3,
          "title": "监听函数的执行顺序是同步 or 异步？",
          "slug": "监听函数的执行顺序是同步-or-异步"
        },
        {
          "level": 3,
          "title": "事件循环中的事件是什么情况下产生的？什么情况下触发的？",
          "slug": "事件循环中的事件是什么情况下产生的-什么情况下触发的"
        },
        {
          "level": 3,
          "title": "事件类型为error的问题",
          "slug": "事件类型为error的问题"
        },
        {
          "level": 3,
          "title": "如何修改EventEmitter的最大监听数量？",
          "slug": "如何修改eventemitter的最大监听数量"
        },
        {
          "level": 2,
          "title": "EventEmitter的应用场景",
          "slug": "eventemitter的应用场景"
        },
        {
          "level": 2,
          "title": "发布/订阅模式与观察者模式的一点说明",
          "slug": "发布-订阅模式与观察者模式的一点说明"
        }
      ]
    },
    {
      "title": "node核心模块 -fs模块",
      "frontmatter": {
        "title": "node核心模块 -fs模块",
        "date": "2019-07-30T00:00:00.000Z",
        "tags": [
          "Node.js"
        ]
      },
      "regularPath": "/node/module_fs.html",
      "relativePath": "node/module_fs.md",
      "key": "v-6e9f767f",
      "path": "/node/module_fs.html",
      "headers": [
        {
          "level": 2,
          "title": "文章概览",
          "slug": "文章概览"
        },
        {
          "level": 2,
          "title": "面试会问",
          "slug": "面试会问"
        },
        {
          "level": 2,
          "title": "文件常识",
          "slug": "文件常识"
        },
        {
          "level": 3,
          "title": "权限位 mode",
          "slug": "权限位-mode"
        },
        {
          "level": 3,
          "title": "标识位 flag",
          "slug": "标识位-flag"
        },
        {
          "level": 3,
          "title": "文件描述符 fs",
          "slug": "文件描述符-fs"
        },
        {
          "level": 2,
          "title": "文件操作",
          "slug": "文件操作"
        },
        {
          "level": 3,
          "title": "完整性读写文件操作",
          "slug": "完整性读写文件操作"
        },
        {
          "level": 3,
          "title": "指定位置读写文件操作(高级文件操作)",
          "slug": "指定位置读写文件操作-高级文件操作"
        },
        {
          "level": 2,
          "title": "目录(文件夹)操作",
          "slug": "目录-文件夹-操作"
        },
        {
          "level": 2,
          "title": "实战训练：",
          "slug": "实战训练"
        },
        {
          "level": 3,
          "title": "「示例：fs 模块如何实现文件拷贝」",
          "slug": "「示例-fs-模块如何实现文件拷贝」"
        }
      ]
    },
    {
      "title": "Node.js 进阶-你应该知道的 npm 知识都在这",
      "frontmatter": {
        "title": "Node.js 进阶-你应该知道的 npm 知识都在这",
        "date": "2020-06-28T00:00:00.000Z",
        "tags": [
          "npm",
          "工具"
        ]
      },
      "regularPath": "/node/npm.html",
      "relativePath": "node/npm.md",
      "key": "v-cb3ceeae",
      "path": "/node/npm.html"
    },
    {
      "title": "Node.js 内存溢出时如何处理？",
      "frontmatter": {
        "title": "Node.js 内存溢出时如何处理？",
        "date": "2019-08-19T00:00:00.000Z",
        "tags": [
          "Node.js"
        ]
      },
      "regularPath": "/node/overflow.html",
      "relativePath": "node/overflow.md",
      "key": "v-1916abd9",
      "path": "/node/overflow.html",
      "headers": [
        {
          "level": 2,
          "title": "本文涵盖",
          "slug": "本文涵盖"
        },
        {
          "level": 2,
          "title": "1.内存溢出问题",
          "slug": "_1-内存溢出问题"
        },
        {
          "level": 2,
          "title": "密集型运算",
          "slug": "密集型运算"
        },
        {
          "level": 2,
          "title": "操作的数据量较大",
          "slug": "操作的数据量较大"
        },
        {
          "level": 2,
          "title": "2. 为什么会内存溢出",
          "slug": "_2-为什么会内存溢出"
        },
        {
          "level": 3,
          "title": "2.1 V8内存分配机制",
          "slug": "_2-1-v8内存分配机制"
        },
        {
          "level": 3,
          "title": "2.2 内存溢出的原因",
          "slug": "_2-2-内存溢出的原因"
        },
        {
          "level": 2,
          "title": "3. 解决内存溢出问题",
          "slug": "_3-解决内存溢出问题"
        },
        {
          "level": 3,
          "title": "3.1. 使用 async/await防止事件堆积,变为同步操作",
          "slug": "_3-1-使用-async-await防止事件堆积-变为同步操作"
        },
        {
          "level": 3,
          "title": "3.2. 增加V8内存空间",
          "slug": "_3-2-增加v8内存空间"
        },
        {
          "level": 3,
          "title": "3.3. 使用非V8内存",
          "slug": "_3-3-使用非v8内存"
        },
        {
          "level": 2,
          "title": "Node系列原创文章",
          "slug": "node系列原创文章"
        },
        {
          "level": 2,
          "title": "关注我",
          "slug": "关注我"
        }
      ]
    },
    {
      "title": "node核心模块 -文件路径path",
      "frontmatter": {
        "title": "node核心模块 -文件路径path",
        "date": "2019-07-30T00:00:00.000Z",
        "tags": [
          "Node.js"
        ]
      },
      "regularPath": "/node/path.html",
      "relativePath": "node/path.md",
      "key": "v-074a5179",
      "path": "/node/path.html",
      "headers": [
        {
          "level": 2,
          "title": "path",
          "slug": "path"
        },
        {
          "level": 3,
          "title": "path.normalize",
          "slug": "path-normalize"
        },
        {
          "level": 3,
          "title": "path.join",
          "slug": "path-join"
        },
        {
          "level": 3,
          "title": "path.parse",
          "slug": "path-parse"
        },
        {
          "level": 3,
          "title": "path.basename",
          "slug": "path-basename"
        },
        {
          "level": 3,
          "title": "path.dirname",
          "slug": "path-dirname"
        },
        {
          "level": 3,
          "title": "path.extname",
          "slug": "path-extname"
        },
        {
          "level": 3,
          "title": "path.resolve",
          "slug": "path-resolve"
        },
        {
          "level": 3,
          "title": "path.relative",
          "slug": "path-relative"
        },
        {
          "level": 2,
          "title": "总结",
          "slug": "总结"
        }
      ]
    },
    {
      "title": "深入理解Node.js 中的进程与线程",
      "frontmatter": {
        "title": "深入理解Node.js 中的进程与线程",
        "date": "2019-08-08T00:00:00.000Z",
        "tags": [
          "Node.js",
          "进程",
          "线程"
        ]
      },
      "regularPath": "/node/processAndThread.html",
      "relativePath": "node/processAndThread.md",
      "key": "v-573684d9",
      "path": "/node/processAndThread.html",
      "headers": [
        {
          "level": 2,
          "title": "文章导览",
          "slug": "文章导览"
        },
        {
          "level": 2,
          "title": "面试会问",
          "slug": "面试会问"
        },
        {
          "level": 2,
          "title": "进程",
          "slug": "进程"
        },
        {
          "level": 2,
          "title": "线程",
          "slug": "线程"
        },
        {
          "level": 3,
          "title": "单线程",
          "slug": "单线程"
        },
        {
          "level": 2,
          "title": "Node.js 中的进程与线程",
          "slug": "node-js-中的进程与线程"
        },
        {
          "level": 3,
          "title": "Node.js 中的进程",
          "slug": "node-js-中的进程"
        },
        {
          "level": 3,
          "title": "Node.js 线程",
          "slug": "node-js-线程"
        },
        {
          "level": 2,
          "title": "总结",
          "slug": "总结"
        }
      ]
    },
    {
      "title": "消息队列助- Node.js实践篇",
      "frontmatter": {
        "title": "消息队列助- Node.js实践篇",
        "date": "2019-11-22T00:00:00.000Z",
        "tags": [
          "Node.js"
        ]
      },
      "regularPath": "/node/queue.html",
      "relativePath": "node/queue.md",
      "key": "v-ac9d7246",
      "path": "/node/queue.html",
      "headers": [
        {
          "level": 2,
          "title": "为什么写这篇文章",
          "slug": "为什么写这篇文章"
        },
        {
          "level": 2,
          "title": "文章导图(你能学到)",
          "slug": "文章导图-你能学到"
        },
        {
          "level": 2,
          "title": "什么是消息队列",
          "slug": "什么是消息队列"
        },
        {
          "level": 3,
          "title": "消息队列优势",
          "slug": "消息队列优势"
        },
        {
          "level": 3,
          "title": "消息队列的类型介绍",
          "slug": "消息队列的类型介绍"
        },
        {
          "level": 2,
          "title": "初识消息队列(消息队列在node.js中的简单应用)",
          "slug": "初识消息队列-消息队列在node-js中的简单应用"
        },
        {
          "level": 3,
          "title": "Rabbitmq基本安装",
          "slug": "rabbitmq基本安装"
        },
        {
          "level": 3,
          "title": "Node.js实现一个简单的 HelloWorld 消息队列",
          "slug": "node-js实现一个简单的-helloworld-消息队列"
        },
        {
          "level": 3,
          "title": "如何释放掉消息队列",
          "slug": "如何释放掉消息队列"
        },
        {
          "level": 2,
          "title": "消息队列交换机讲解",
          "slug": "消息队列交换机讲解"
        },
        {
          "level": 3,
          "title": "交换机的种类",
          "slug": "交换机的种类"
        },
        {
          "level": 2,
          "title": "消息队列的思考与深入探索",
          "slug": "消息队列的思考与深入探索"
        },
        {
          "level": 3,
          "title": "消息队列实现rpc",
          "slug": "消息队列实现rpc"
        },
        {
          "level": 3,
          "title": "是否有消息持久化的必要？",
          "slug": "是否有消息持久化的必要"
        },
        {
          "level": 3,
          "title": "消费者完成后是否有消息应答的必要？",
          "slug": "消费者完成后是否有消息应答的必要"
        },
        {
          "level": 3,
          "title": "如何实现公平调度？",
          "slug": "如何实现公平调度"
        },
        {
          "level": 3,
          "title": "如何实现一个交换机给多个消费者依次发送消息，选择那种交换机？",
          "slug": "如何实现一个交换机给多个消费者依次发送消息-选择那种交换机"
        },
        {
          "level": 2,
          "title": "消息队列应用场景",
          "slug": "消息队列应用场景"
        },
        {
          "level": 2,
          "title": "总结",
          "slug": "总结"
        },
        {
          "level": 2,
          "title": "参考文章",
          "slug": "参考文章"
        },
        {
          "level": 2,
          "title": "Node系列原创文章",
          "slug": "node系列原创文章"
        },
        {
          "level": 3,
          "title": "关注我",
          "slug": "关注我"
        }
      ]
    },
    {
      "title": "Node.js中stream模块详解",
      "frontmatter": {
        "title": "Node.js中stream模块详解",
        "date": "2019-06-14T00:00:00.000Z",
        "tags": [
          "Node.js"
        ]
      },
      "regularPath": "/node/stream.html",
      "relativePath": "node/stream.md",
      "key": "v-222a7cd9",
      "path": "/node/stream.html",
      "headers": [
        {
          "level": 3,
          "title": "stream定义",
          "slug": "stream定义"
        },
        {
          "level": 2,
          "title": "为什么要学习stream",
          "slug": "为什么要学习stream"
        },
        {
          "level": 3,
          "title": "视频播放例子",
          "slug": "视频播放例子"
        },
        {
          "level": 3,
          "title": "读取大文件data的例子",
          "slug": "读取大文件data的例子"
        },
        {
          "level": 2,
          "title": "stream流转过程",
          "slug": "stream流转过程"
        },
        {
          "level": 3,
          "title": "stream从哪里来-soucre",
          "slug": "stream从哪里来-soucre"
        },
        {
          "level": 3,
          "title": "连接水桶的管道-pipe",
          "slug": "连接水桶的管道-pipe"
        },
        {
          "level": 3,
          "title": "stream到哪里去-dest",
          "slug": "stream到哪里去-dest"
        },
        {
          "level": 2,
          "title": "stream应用场景",
          "slug": "stream应用场景"
        },
        {
          "level": 3,
          "title": "介绍一个压力测试的小工具",
          "slug": "介绍一个压力测试的小工具"
        },
        {
          "level": 3,
          "title": "get请求中应用stream",
          "slug": "get请求中应用stream"
        },
        {
          "level": 3,
          "title": "post中使用stream",
          "slug": "post中使用stream"
        },
        {
          "level": 3,
          "title": "post与get使用stream总结",
          "slug": "post与get使用stream总结"
        },
        {
          "level": 3,
          "title": "在文件操作中使用stream",
          "slug": "在文件操作中使用stream"
        },
        {
          "level": 3,
          "title": "前端一些打包工具的底层实现",
          "slug": "前端一些打包工具的底层实现"
        },
        {
          "level": 2,
          "title": "stream的种类",
          "slug": "stream的种类"
        },
        {
          "level": 2,
          "title": "stream有什么弊端",
          "slug": "stream有什么弊端"
        },
        {
          "level": 2,
          "title": "stream的常见类库",
          "slug": "stream的常见类库"
        },
        {
          "level": 2,
          "title": "总结",
          "slug": "总结"
        }
      ]
    },
    {
      "title": "看这里，能知道 Node.js 究竟是什么",
      "frontmatter": {
        "title": "看这里，能知道 Node.js 究竟是什么",
        "date": "2019-06-09T00:00:00.000Z",
        "tags": [
          "Node.js"
        ]
      },
      "regularPath": "/node/what.html",
      "relativePath": "node/what.md",
      "key": "v-e6f459ce",
      "path": "/node/what.html",
      "headers": [
        {
          "level": 2,
          "title": "Node.js的特点",
          "slug": "node-js的特点"
        },
        {
          "level": 2,
          "title": "Node.js的弊端",
          "slug": "node-js的弊端"
        },
        {
          "level": 3,
          "title": "单线程带来的弊端",
          "slug": "单线程带来的弊端"
        },
        {
          "level": 3,
          "title": "调试",
          "slug": "调试"
        },
        {
          "level": 3,
          "title": "Node社区中的npm包",
          "slug": "node社区中的npm包"
        },
        {
          "level": 2,
          "title": "Node.js的应用场景",
          "slug": "node-js的应用场景"
        },
        {
          "level": 2,
          "title": "哪些大公司在用",
          "slug": "哪些大公司在用"
        }
      ]
    },
    {
      "title": "书籍推荐",
      "frontmatter": {
        "title": "书籍推荐",
        "date": "2019-05-01T00:00:00.000Z",
        "tags": [
          "电子书"
        ]
      },
      "regularPath": "/recommend/book.html",
      "relativePath": "recommend/book.md",
      "key": "v-3439a0ad",
      "path": "/recommend/book.html",
      "headers": [
        {
          "level": 2,
          "title": "Javascript系列",
          "slug": "javascript系列"
        },
        {
          "level": 2,
          "title": "Node.js系列",
          "slug": "node-js系列"
        },
        {
          "level": 2,
          "title": "算法系列",
          "slug": "算法系列"
        },
        {
          "level": 2,
          "title": "数据库系列",
          "slug": "数据库系列"
        }
      ]
    },
    {
      "title": "开源项目汇总",
      "frontmatter": {
        "title": "开源项目汇总",
        "date": "2019-07-10T00:00:00.000Z",
        "tags": [
          "其他"
        ]
      },
      "regularPath": "/recommend/project.html",
      "relativePath": "recommend/project.md",
      "key": "v-3b49be0e",
      "path": "/recommend/project.html",
      "headers": [
        {
          "level": 2,
          "title": "vue开源项目",
          "slug": "vue开源项目"
        },
        {
          "level": 2,
          "title": "react开源项目",
          "slug": "react开源项目"
        },
        {
          "level": 2,
          "title": "其他",
          "slug": "其他"
        }
      ]
    },
    {
      "frontmatter": {},
      "regularPath": "/tags/",
      "relativePath": "tags/README.md",
      "key": "v-568a1ef2",
      "path": "/tags/"
    },
    {
      "title": "Typescript系列之接口篇",
      "frontmatter": {
        "title": "Typescript系列之接口篇",
        "date": "2019-11-18T00:00:00.000Z",
        "tags": [
          "Typescript"
        ]
      },
      "regularPath": "/typescript/interface.html",
      "relativePath": "typescript/interface.md",
      "key": "v-53b30d47",
      "path": "/typescript/interface.html",
      "headers": [
        {
          "level": 2,
          "title": "接口带来了什么好处",
          "slug": "接口带来了什么好处"
        },
        {
          "level": 3,
          "title": "好处One —— 过去我们写 JavaScript",
          "slug": "好处one-过去我们写-javascript"
        },
        {
          "level": 3,
          "title": "好处TWO —— 过去我们用 Node.js 写后端接口",
          "slug": "好处two-过去我们用-node-js-写后端接口"
        },
        {
          "level": 2,
          "title": "接口的基础篇",
          "slug": "接口的基础篇"
        },
        {
          "level": 3,
          "title": "接口的定义",
          "slug": "接口的定义"
        },
        {
          "level": 3,
          "title": "接口中定义方法",
          "slug": "接口中定义方法"
        },
        {
          "level": 3,
          "title": "接口中定义属性",
          "slug": "接口中定义属性"
        },
        {
          "level": 2,
          "title": "接口的高级篇",
          "slug": "接口的高级篇"
        },
        {
          "level": 3,
          "title": "函数类型接口",
          "slug": "函数类型接口"
        },
        {
          "level": 3,
          "title": "接口的实现",
          "slug": "接口的实现"
        },
        {
          "level": 3,
          "title": "接口的继承",
          "slug": "接口的继承"
        },
        {
          "level": 3,
          "title": "可索引类型接口",
          "slug": "可索引类型接口"
        },
        {
          "level": 3,
          "title": "interface和type的区别",
          "slug": "interface和type的区别"
        },
        {
          "level": 2,
          "title": "接口的应用场景总结",
          "slug": "接口的应用场景总结"
        },
        {
          "level": 2,
          "title": "总结",
          "slug": "总结"
        },
        {
          "level": 2,
          "title": "参考文章",
          "slug": "参考文章"
        },
        {
          "level": 3,
          "title": "关注我",
          "slug": "关注我"
        }
      ]
    },
    {
      "title": "前端文章目录",
      "frontmatter": {},
      "regularPath": "/webframe/",
      "relativePath": "webframe/README.md",
      "key": "v-72ac281c",
      "path": "/webframe/",
      "headers": [
        {
          "level": 3,
          "title": "前端文章目录",
          "slug": "前端文章目录"
        },
        {
          "level": 2,
          "title": "交流群里讨论问题整理",
          "slug": "交流群里讨论问题整理"
        }
      ]
    },
    {
      "title": "10个css高频面试题",
      "frontmatter": {
        "title": "10个css高频面试题",
        "date": "2019-05-19T00:00:00.000Z",
        "tags": [
          "CSS"
        ]
      },
      "regularPath": "/webframe/css/1.html",
      "relativePath": "webframe/css/1.md",
      "key": "v-db5130f2",
      "path": "/webframe/css/1.html",
      "headers": [
        {
          "level": 2,
          "title": "快速导航",
          "slug": "快速导航"
        },
        {
          "level": 2,
          "title": "1.BFC机制",
          "slug": "_1-bfc机制"
        },
        {
          "level": 2,
          "title": "2.CSS3中新增的选择器以及属性",
          "slug": "_2-css3中新增的选择器以及属性"
        },
        {
          "level": 2,
          "title": "3.居中布局",
          "slug": "_3-居中布局"
        },
        {
          "level": 2,
          "title": "4.清除浮动有哪些方法,各有什么优缺点",
          "slug": "_4-清除浮动有哪些方法-各有什么优缺点"
        },
        {
          "level": 2,
          "title": "5.用纯CSS创建一个三角形的原理是什么",
          "slug": "_5-用纯css创建一个三角形的原理是什么"
        },
        {
          "level": 2,
          "title": "6.实现三栏布局有哪些方法, 分别描述一下",
          "slug": "_6-实现三栏布局有哪些方法-分别描述一下"
        },
        {
          "level": 2,
          "title": "7.css3实现0.5px的细线",
          "slug": "_7-css3实现0-5px的细线"
        },
        {
          "level": 2,
          "title": "8.link 与 @import 的区别",
          "slug": "_8-link-与-import-的区别"
        },
        {
          "level": 2,
          "title": "9.开发中为什么要初始化css样式",
          "slug": "_9-开发中为什么要初始化css样式"
        },
        {
          "level": 2,
          "title": "10.CSS优化、提高性能的方法有哪些",
          "slug": "_10-css优化、提高性能的方法有哪些"
        }
      ]
    },
    {
      "title": "目录",
      "frontmatter": {},
      "regularPath": "/webframe/css/",
      "relativePath": "webframe/css/readme.md",
      "key": "v-4e72c11c",
      "path": "/webframe/css/",
      "headers": [
        {
          "level": 2,
          "title": "目录",
          "slug": "目录"
        },
        {
          "level": 2,
          "title": "交流群问题整理",
          "slug": "交流群问题整理"
        }
      ]
    },
    {
      "title": "渲染树的形成原理",
      "frontmatter": {
        "title": "渲染树的形成原理",
        "date": "2019-10-28T00:00:00.000Z",
        "tags": [
          "浏览器"
        ]
      },
      "regularPath": "/webframe/css/render.html",
      "relativePath": "webframe/css/render.md",
      "key": "v-6cadae39",
      "path": "/webframe/css/render.html",
      "headers": [
        {
          "level": 2,
          "title": "系列文章",
          "slug": "系列文章"
        },
        {
          "level": 2,
          "title": "什么是DOM",
          "slug": "什么是dom"
        },
        {
          "level": 2,
          "title": "渲染树最终形成经历了哪些",
          "slug": "渲染树最终形成经历了哪些"
        },
        {
          "level": 3,
          "title": "HTML解析器",
          "slug": "html解析器"
        },
        {
          "level": 3,
          "title": "CSS解析器",
          "slug": "css解析器"
        },
        {
          "level": 3,
          "title": "javascript对DOM树与CSSOM树创建的影响",
          "slug": "javascript对dom树与cssom树创建的影响"
        },
        {
          "level": 3,
          "title": "构建渲染树",
          "slug": "构建渲染树"
        },
        {
          "level": 3,
          "title": "本文渲染树形成过程可以做哪些优化",
          "slug": "本文渲染树形成过程可以做哪些优化"
        },
        {
          "level": 3,
          "title": "总结",
          "slug": "总结"
        },
        {
          "level": 3,
          "title": "参考资料:",
          "slug": "参考资料"
        },
        {
          "level": 3,
          "title": "关注我",
          "slug": "关注我"
        }
      ]
    },
    {
      "title": "es6 目录",
      "frontmatter": {},
      "regularPath": "/webframe/es6/",
      "relativePath": "webframe/es6/README.md",
      "key": "v-33ca55dc",
      "path": "/webframe/es6/",
      "headers": [
        {
          "level": 2,
          "title": "es6 目录",
          "slug": "es6-目录"
        }
      ]
    },
    {
      "title": "async和await的讲解",
      "frontmatter": {
        "title": "async和await的讲解",
        "date": "2019-05-10T00:00:00.000Z",
        "tags": [
          "ES6",
          "await",
          "async"
        ]
      },
      "regularPath": "/webframe/es6/async-await.html",
      "relativePath": "webframe/es6/async-await.md",
      "key": "v-4db130d5",
      "path": "/webframe/es6/async-await.html",
      "headers": [
        {
          "level": 3,
          "title": "声明async函数的几个方法",
          "slug": "声明async函数的几个方法"
        },
        {
          "level": 3,
          "title": "初识async和await",
          "slug": "初识async和await"
        },
        {
          "level": 3,
          "title": "async与await缺点",
          "slug": "async与await缺点"
        },
        {
          "level": 3,
          "title": "await与async大多数人的误区",
          "slug": "await与async大多数人的误区"
        }
      ]
    },
    {
      "title": "es6中的class学习(对比java)",
      "frontmatter": {
        "title": "es6中的class学习(对比java)",
        "date": "2019-06-10T00:00:00.000Z",
        "tags": [
          "ES6",
          "class"
        ]
      },
      "regularPath": "/webframe/es6/classInherit.html",
      "relativePath": "webframe/es6/classInherit.md",
      "key": "v-c2a60a8e",
      "path": "/webframe/es6/classInherit.html",
      "headers": [
        {
          "level": 2,
          "title": "前言",
          "slug": "前言"
        },
        {
          "level": 2,
          "title": "类中的变量",
          "slug": "类中的变量"
        },
        {
          "level": 2,
          "title": "类中的构造函数",
          "slug": "类中的构造函数"
        },
        {
          "level": 2,
          "title": "类中的方法",
          "slug": "类中的方法"
        },
        {
          "level": 2,
          "title": "类中的继承",
          "slug": "类中的继承"
        },
        {
          "level": 2,
          "title": "ES6中的类与原型链的关系",
          "slug": "es6中的类与原型链的关系"
        },
        {
          "level": 2,
          "title": "ES6中类的出现有什么好处",
          "slug": "es6中类的出现有什么好处"
        }
      ]
    },
    {
      "title": "ES6中的Promise",
      "frontmatter": {
        "title": "ES6中的Promise",
        "date": "2019-08-04T00:00:00.000Z",
        "tags": [
          "ES6"
        ]
      },
      "regularPath": "/webframe/es6/promise.html",
      "relativePath": "webframe/es6/promise.md",
      "key": "v-7ad91ba9",
      "path": "/webframe/es6/promise.html",
      "headers": [
        {
          "level": 2,
          "title": "为什么出现Promise",
          "slug": "为什么出现promise"
        },
        {
          "level": 2,
          "title": "Promise的含义",
          "slug": "promise的含义"
        },
        {
          "level": 2,
          "title": "Promise原理与讲解",
          "slug": "promise原理与讲解"
        },
        {
          "level": 2,
          "title": "Promise在开发中的应用",
          "slug": "promise在开发中的应用"
        },
        {
          "level": 2,
          "title": "Promise使用过程中注意事项与误区",
          "slug": "promise使用过程中注意事项与误区"
        },
        {
          "level": 2,
          "title": "Promise的反思",
          "slug": "promise的反思"
        }
      ]
    },
    {
      "title": "目录",
      "frontmatter": {},
      "regularPath": "/webframe/html/",
      "relativePath": "webframe/html/README.md",
      "key": "v-552ce47e",
      "path": "/webframe/html/",
      "headers": [
        {
          "level": 2,
          "title": "目录",
          "slug": "目录"
        },
        {
          "level": 3,
          "title": "html内容",
          "slug": "html内容"
        },
        {
          "level": 2,
          "title": "群内交流问题",
          "slug": "群内交流问题"
        }
      ]
    },
    {
      "title": "目录",
      "frontmatter": {},
      "regularPath": "/webframe/javascript/",
      "relativePath": "webframe/javascript/README.md",
      "key": "v-378a030c",
      "path": "/webframe/javascript/",
      "headers": [
        {
          "level": 2,
          "title": "目录",
          "slug": "目录"
        },
        {
          "level": 2,
          "title": "交流群讨论问题整理(整理中)",
          "slug": "交流群讨论问题整理-整理中"
        }
      ]
    },
    {
      "title": "javascript中的闭包",
      "frontmatter": {
        "title": "javascript中的闭包",
        "date": "2019-06-05T00:00:00.000Z",
        "tags": [
          "Javascript"
        ]
      },
      "regularPath": "/webframe/javascript/closure.html",
      "relativePath": "webframe/javascript/closure.md",
      "key": "v-43960319",
      "path": "/webframe/javascript/closure.html",
      "headers": [
        {
          "level": 2,
          "title": "快速导航",
          "slug": "快速导航"
        },
        {
          "level": 2,
          "title": "什么是闭包",
          "slug": "什么是闭包"
        },
        {
          "level": 2,
          "title": "闭包的常见案例分析",
          "slug": "闭包的常见案例分析"
        },
        {
          "level": 2,
          "title": "闭包与内存泄漏",
          "slug": "闭包与内存泄漏"
        },
        {
          "level": 2,
          "title": "闭包的应用",
          "slug": "闭包的应用"
        },
        {
          "level": 2,
          "title": "面试题分析",
          "slug": "面试题分析"
        },
        {
          "level": 2,
          "title": "总结",
          "slug": "总结"
        }
      ]
    },
    {
      "title": "搞不懂JS中赋值·浅拷贝·深拷贝的请看这里",
      "frontmatter": {
        "title": "搞不懂JS中赋值·浅拷贝·深拷贝的请看这里",
        "date": "2019-07-14T00:00:00.000Z",
        "tags": [
          "Javascript"
        ]
      },
      "regularPath": "/webframe/javascript/copy.html",
      "relativePath": "webframe/javascript/copy.md",
      "key": "v-142e22e3",
      "path": "/webframe/javascript/copy.html",
      "headers": [
        {
          "level": 2,
          "title": "前言",
          "slug": "前言"
        },
        {
          "level": 2,
          "title": "数据类型与堆栈的关系",
          "slug": "数据类型与堆栈的关系"
        },
        {
          "level": 3,
          "title": "基本类型与引用类型",
          "slug": "基本类型与引用类型"
        },
        {
          "level": 3,
          "title": "存储方式",
          "slug": "存储方式"
        },
        {
          "level": 2,
          "title": "赋值操作",
          "slug": "赋值操作"
        },
        {
          "level": 3,
          "title": "基本数据类型复制",
          "slug": "基本数据类型复制"
        },
        {
          "level": 3,
          "title": "引用数据类型复制",
          "slug": "引用数据类型复制"
        },
        {
          "level": 2,
          "title": "浅拷贝",
          "slug": "浅拷贝"
        },
        {
          "level": 3,
          "title": "浅拷贝定义：",
          "slug": "浅拷贝定义"
        },
        {
          "level": 3,
          "title": "浅拷贝实例",
          "slug": "浅拷贝实例"
        },
        {
          "level": 3,
          "title": "自己实现一个浅拷贝",
          "slug": "自己实现一个浅拷贝"
        },
        {
          "level": 2,
          "title": "深拷贝操作",
          "slug": "深拷贝操作"
        },
        {
          "level": 3,
          "title": "深拷贝定义",
          "slug": "深拷贝定义"
        },
        {
          "level": 3,
          "title": "深拷贝实例",
          "slug": "深拷贝实例"
        },
        {
          "level": 2,
          "title": "拷贝内容总结",
          "slug": "拷贝内容总结"
        }
      ]
    },
    {
      "title": "面试常问javascript数据类型",
      "frontmatter": {
        "title": "面试常问javascript数据类型",
        "date": "2019-06-14T00:00:00.000Z",
        "tags": [
          "Javascript"
        ]
      },
      "regularPath": "/webframe/javascript/datatype.html",
      "relativePath": "webframe/javascript/datatype.md",
      "key": "v-40d5d845",
      "path": "/webframe/javascript/datatype.html",
      "headers": [
        {
          "level": 2,
          "title": "前言",
          "slug": "前言"
        },
        {
          "level": 2,
          "title": "快速导航",
          "slug": "快速导航"
        },
        {
          "level": 3,
          "title": "常见面试题",
          "slug": "常见面试题"
        },
        {
          "level": 2,
          "title": "js中的数据类型",
          "slug": "js中的数据类型"
        },
        {
          "level": 3,
          "title": "基本类型",
          "slug": "基本类型"
        },
        {
          "level": 3,
          "title": "对象类型",
          "slug": "对象类型"
        },
        {
          "level": 3,
          "title": "ToPrimitive(转换为原始值)",
          "slug": "toprimitive-转换为原始值"
        },
        {
          "level": 3,
          "title": "toString",
          "slug": "tostring"
        },
        {
          "level": 3,
          "title": "valueOf",
          "slug": "valueof"
        },
        {
          "level": 3,
          "title": "Number",
          "slug": "number"
        },
        {
          "level": 3,
          "title": "String",
          "slug": "string"
        },
        {
          "level": 3,
          "title": "Boolean",
          "slug": "boolean"
        },
        {
          "level": 3,
          "title": "什么时候自动转换为string类型",
          "slug": "什么时候自动转换为string类型"
        },
        {
          "level": 3,
          "title": "什么时候自动转换为Number类型",
          "slug": "什么时候自动转换为number类型"
        },
        {
          "level": 3,
          "title": "什么时候进行布尔转换",
          "slug": "什么时候进行布尔转换"
        },
        {
          "level": 3,
          "title": "typeof",
          "slug": "typeof"
        },
        {
          "level": 3,
          "title": "instanceof",
          "slug": "instanceof"
        },
        {
          "level": 3,
          "title": "Object.prototype.toString()",
          "slug": "object-prototype-tostring"
        },
        {
          "level": 3,
          "title": "NaN的概念",
          "slug": "nan的概念"
        },
        {
          "level": 3,
          "title": "什么时候返回NaN （开篇第二道题也得到解决）",
          "slug": "什么时候返回nan-开篇第二道题也得到解决"
        },
        {
          "level": 3,
          "title": "toString和String的区别",
          "slug": "tostring和string的区别"
        }
      ]
    },
    {
      "frontmatter": {},
      "regularPath": "/webframe/javascript/es6WidelyUsed.html",
      "relativePath": "webframe/javascript/es6WidelyUsed.md",
      "key": "v-97e69dce",
      "path": "/webframe/javascript/es6WidelyUsed.html"
    },
    {
      "title": "exports 和 module.exports",
      "frontmatter": {
        "title": "exports 和 module.exports",
        "date": "2019-08-16T00:00:00.000Z",
        "tags": [
          "Javascript"
        ]
      },
      "regularPath": "/webframe/javascript/exports.html",
      "relativePath": "webframe/javascript/exports.md",
      "key": "v-092fd399",
      "path": "/webframe/javascript/exports.html",
      "headers": [
        {
          "level": 2,
          "title": "面试会问",
          "slug": "面试会问"
        },
        {
          "level": 2,
          "title": "require",
          "slug": "require"
        },
        {
          "level": 3,
          "title": "require 重复引入问题",
          "slug": "require-重复引入问题"
        },
        {
          "level": 3,
          "title": "require 加载模块的时候是同步还是异步？",
          "slug": "require-加载模块的时候是同步还是异步"
        },
        {
          "level": 3,
          "title": "require() 的缓存策略",
          "slug": "require-的缓存策略"
        },
        {
          "level": 2,
          "title": "exports 与 module.exports 区别",
          "slug": "exports-与-module-exports-区别"
        },
        {
          "level": 3,
          "title": "js文件启动时",
          "slug": "js文件启动时"
        },
        {
          "level": 3,
          "title": "require()加载模块",
          "slug": "require-加载模块"
        },
        {
          "level": 3,
          "title": "官网中的一个例子",
          "slug": "官网中的一个例子"
        },
        {
          "level": 3,
          "title": "使用的一点建议",
          "slug": "使用的一点建议"
        }
      ]
    },
    {
      "title": "高阶函数详解与实战训练",
      "frontmatter": {
        "title": "高阶函数详解与实战训练",
        "date": "2019-08-20T00:00:00.000Z",
        "tags": [
          "Javascript"
        ]
      },
      "regularPath": "/webframe/javascript/higherFunc.html",
      "relativePath": "webframe/javascript/higherFunc.md",
      "key": "v-057c5cb2",
      "path": "/webframe/javascript/higherFunc.html",
      "headers": [
        {
          "level": 2,
          "title": "前言",
          "slug": "前言"
        },
        {
          "level": 2,
          "title": "高阶函数定义",
          "slug": "高阶函数定义"
        },
        {
          "level": 2,
          "title": "函数作为参数情况",
          "slug": "函数作为参数情况"
        },
        {
          "level": 2,
          "title": "Array.prototype.map",
          "slug": "array-prototype-map"
        },
        {
          "level": 3,
          "title": "不使用高阶函数",
          "slug": "不使用高阶函数"
        },
        {
          "level": 3,
          "title": "使用高阶函数",
          "slug": "使用高阶函数"
        },
        {
          "level": 3,
          "title": "map高阶函数注意点",
          "slug": "map高阶函数注意点"
        },
        {
          "level": 3,
          "title": "map高阶函数对应的一道经典面试题",
          "slug": "map高阶函数对应的一道经典面试题"
        },
        {
          "level": 2,
          "title": "Array.prototype.reduce",
          "slug": "array-prototype-reduce"
        },
        {
          "level": 3,
          "title": "不使用高阶函数",
          "slug": "不使用高阶函数-2"
        },
        {
          "level": 3,
          "title": "使用高阶函数",
          "slug": "使用高阶函数-2"
        },
        {
          "level": 2,
          "title": "Array.prototype.filter",
          "slug": "array-prototype-filter"
        },
        {
          "level": 3,
          "title": "不使用高阶函数",
          "slug": "不使用高阶函数-3"
        },
        {
          "level": 3,
          "title": "使用高阶函数",
          "slug": "使用高阶函数-3"
        },
        {
          "level": 3,
          "title": "filter注意点说明",
          "slug": "filter注意点说明"
        },
        {
          "level": 2,
          "title": "Array.prototype.sort",
          "slug": "array-prototype-sort"
        },
        {
          "level": 3,
          "title": "sort排序算法的底层实现",
          "slug": "sort排序算法的底层实现"
        },
        {
          "level": 3,
          "title": "如何改进排序算法实现数字正确排序呢？",
          "slug": "如何改进排序算法实现数字正确排序呢"
        },
        {
          "level": 2,
          "title": "函数作为返回值输出",
          "slug": "函数作为返回值输出"
        },
        {
          "level": 3,
          "title": "isType 函数",
          "slug": "istype-函数"
        },
        {
          "level": 3,
          "title": "add求和函数",
          "slug": "add求和函数"
        },
        {
          "level": 2,
          "title": "如何自己创建高阶函数",
          "slug": "如何自己创建高阶函数"
        },
        {
          "level": 3,
          "title": "代码分析讲解：",
          "slug": "代码分析讲解"
        },
        {
          "level": 2,
          "title": "总结",
          "slug": "总结"
        },
        {
          "level": 3,
          "title": "公众号技术栈路线",
          "slug": "公众号技术栈路线"
        },
        {
          "level": 3,
          "title": "加入我们",
          "slug": "加入我们"
        }
      ]
    },
    {
      "title": "javascript中的原型链",
      "frontmatter": {
        "title": "javascript中的原型链",
        "date": "2019-06-19T00:00:00.000Z",
        "tags": [
          "Javascript"
        ]
      },
      "regularPath": "/webframe/javascript/prototype.html",
      "relativePath": "webframe/javascript/prototype.md",
      "key": "v-b7adee0e",
      "path": "/webframe/javascript/prototype.html",
      "headers": [
        {
          "level": 2,
          "title": "对象着手",
          "slug": "对象着手"
        },
        {
          "level": 3,
          "title": "prototype与__proto__两个概念",
          "slug": "prototype与-proto-两个概念"
        },
        {
          "level": 2,
          "title": "原型链详解",
          "slug": "原型链详解"
        },
        {
          "level": 3,
          "title": "代码对象原型链图:",
          "slug": "代码对象原型链图"
        },
        {
          "level": 3,
          "title": "对象访问属性顺序",
          "slug": "对象访问属性顺序"
        },
        {
          "level": 3,
          "title": "in，hasOwnProperty等方法的出现",
          "slug": "in-hasownproperty等方法的出现"
        },
        {
          "level": 3,
          "title": "特殊说明",
          "slug": "特殊说明"
        },
        {
          "level": 2,
          "title": "总结",
          "slug": "总结"
        },
        {
          "level": 3,
          "title": "到底什么是原型链?",
          "slug": "到底什么是原型链"
        },
        {
          "level": 3,
          "title": "误区",
          "slug": "误区"
        }
      ]
    },
    {
      "title": "聊聊面试必考-递归思想与实战",
      "frontmatter": {
        "title": "聊聊面试必考-递归思想与实战",
        "date": "2019-10-09T00:00:00.000Z",
        "tags": [
          "Javascript"
        ]
      },
      "regularPath": "/webframe/javascript/recircleFun.html",
      "relativePath": "webframe/javascript/recircleFun.md",
      "key": "v-6a89a78e",
      "path": "/webframe/javascript/recircleFun.html",
      "headers": [
        {
          "level": 2,
          "title": "本篇文章你将学到",
          "slug": "本篇文章你将学到"
        },
        {
          "level": 2,
          "title": "为什么要写这篇文章",
          "slug": "为什么要写这篇文章"
        },
        {
          "level": 2,
          "title": "递归算法是什么",
          "slug": "递归算法是什么"
        },
        {
          "level": 2,
          "title": "递归算法思想讲解用和注意事项",
          "slug": "递归算法思想讲解用和注意事项"
        },
        {
          "level": 3,
          "title": "什么时候使用递归?",
          "slug": "什么时候使用递归"
        },
        {
          "level": 3,
          "title": "如何写递归代码？(满足上面条件，确认使用递归后)",
          "slug": "如何写递归代码-满足上面条件-确认使用递归后"
        },
        {
          "level": 3,
          "title": "写递归代码时注意事项",
          "slug": "写递归代码时注意事项"
        },
        {
          "level": 3,
          "title": "递归算法的一点感悟",
          "slug": "递归算法的一点感悟"
        },
        {
          "level": 2,
          "title": "递归算法使用场景(开篇提到的几个面试题)",
          "slug": "递归算法使用场景-开篇提到的几个面试题"
        },
        {
          "level": 3,
          "title": "1.经典走台阶问题",
          "slug": "_1-经典走台阶问题"
        },
        {
          "level": 3,
          "title": "2.四级分销-找到最佳推荐人",
          "slug": "_2-四级分销-找到最佳推荐人"
        },
        {
          "level": 3,
          "title": "3.数组拍平",
          "slug": "_3-数组拍平"
        },
        {
          "level": 3,
          "title": "4.对象格式化",
          "slug": "_4-对象格式化"
        },
        {
          "level": 3,
          "title": "5.实现一个深拷贝",
          "slug": "_5-实现一个深拷贝"
        },
        {
          "level": 2,
          "title": "总结",
          "slug": "总结"
        },
        {
          "level": 2,
          "title": "参考文章",
          "slug": "参考文章"
        }
      ]
    },
    {
      "title": "javascript中作用域与作用域链",
      "frontmatter": {
        "title": "javascript中作用域与作用域链",
        "date": "2019-06-27T00:00:00.000Z",
        "tags": [
          "Javascript"
        ]
      },
      "regularPath": "/webframe/javascript/scoped.html",
      "relativePath": "webframe/javascript/scoped.md",
      "key": "v-84983526",
      "path": "/webframe/javascript/scoped.html",
      "headers": [
        {
          "level": 2,
          "title": "快速导航",
          "slug": "快速导航"
        },
        {
          "level": 2,
          "title": "1.什么是作用域",
          "slug": "_1-什么是作用域"
        },
        {
          "level": 2,
          "title": "2.JavaScript中的作用域",
          "slug": "_2-javascript中的作用域"
        },
        {
          "level": 3,
          "title": "2.1全局作用域",
          "slug": "_2-1全局作用域"
        },
        {
          "level": 3,
          "title": "2.2局部作用域",
          "slug": "_2-2局部作用域"
        },
        {
          "level": 2,
          "title": "3.作用域链",
          "slug": "_3-作用域链"
        },
        {
          "level": 3,
          "title": "3.1JavaScript是如何执行的？",
          "slug": "_3-1javascript是如何执行的"
        },
        {
          "level": 3,
          "title": "3.2作用域链概念",
          "slug": "_3-2作用域链概念"
        },
        {
          "level": 3,
          "title": "3.3找过程LHS和RHS查询特殊说明",
          "slug": "_3-3找过程lhs和rhs查询特殊说明"
        },
        {
          "level": 3,
          "title": "3.4作用域链总结",
          "slug": "_3-4作用域链总结"
        }
      ]
    },
    {
      "title": "this关键字",
      "frontmatter": {
        "title": "this关键字",
        "date": "2019-09-09T00:00:00.000Z",
        "tags": [
          "Javascript"
        ]
      },
      "regularPath": "/webframe/javascript/this.html",
      "relativePath": "webframe/javascript/this.md",
      "key": "v-7ac73f51",
      "path": "/webframe/javascript/this.html",
      "headers": [
        {
          "level": 2,
          "title": "为什么要学习this关键字",
          "slug": "为什么要学习this关键字"
        },
        {
          "level": 2,
          "title": "文章概览图",
          "slug": "文章概览图"
        },
        {
          "level": 2,
          "title": "函数调用",
          "slug": "函数调用"
        },
        {
          "level": 3,
          "title": "Node.js 环境下指向全局的this关键字说明(你可能不知道)",
          "slug": "node-js-环境下指向全局的this关键字说明-你可能不知道"
        },
        {
          "level": 3,
          "title": "[]语法中的this关键字",
          "slug": "语法中的this关键字"
        },
        {
          "level": 2,
          "title": "this绑定原则",
          "slug": "this绑定原则"
        },
        {
          "level": 3,
          "title": "默认绑定",
          "slug": "默认绑定"
        },
        {
          "level": 3,
          "title": "隐式绑定",
          "slug": "隐式绑定"
        },
        {
          "level": 3,
          "title": "显式绑定",
          "slug": "显式绑定"
        },
        {
          "level": 3,
          "title": "new 绑定",
          "slug": "new-绑定"
        },
        {
          "level": 2,
          "title": "this绑定优先级",
          "slug": "this绑定优先级"
        },
        {
          "level": 2,
          "title": "箭头函数中的 this",
          "slug": "箭头函数中的-this"
        },
        {
          "level": 3,
          "title": "箭头函数",
          "slug": "箭头函数"
        },
        {
          "level": 3,
          "title": "自执行函数",
          "slug": "自执行函数"
        },
        {
          "level": 2,
          "title": "this应用场景",
          "slug": "this应用场景"
        },
        {
          "level": 2,
          "title": "学后小练习",
          "slug": "学后小练习"
        },
        {
          "level": 2,
          "title": "参考文章",
          "slug": "参考文章"
        }
      ]
    },
    {
      "title": "js中数组去重",
      "frontmatter": {
        "title": "js中数组去重",
        "date": "2019-12-26T00:00:00.000Z",
        "tags": [
          "Javascript"
        ]
      },
      "regularPath": "/webframe/javascript/unique.html",
      "relativePath": "webframe/javascript/unique.md",
      "key": "v-52d1902a",
      "path": "/webframe/javascript/unique.html",
      "headers": [
        {
          "level": 2,
          "title": "为什么写这篇文章？",
          "slug": "为什么写这篇文章"
        },
        {
          "level": 2,
          "title": "当面试官问到时怎么回答？",
          "slug": "当面试官问到时怎么回答"
        },
        {
          "level": 3,
          "title": "首先:我知道多少种去重方式",
          "slug": "首先-我知道多少种去重方式"
        },
        {
          "level": 3,
          "title": "然后:询问面试官具体场景",
          "slug": "然后-询问面试官具体场景"
        },
        {
          "level": 3,
          "title": "性能考虑(是想要最快的速度查到数据吗？)",
          "slug": "性能考虑-是想要最快的速度查到数据吗"
        },
        {
          "level": 3,
          "title": "兼容性与场景考虑(数组中是否包含对象，NaN等？)",
          "slug": "兼容性与场景考虑-数组中是否包含对象-nan等"
        },
        {
          "level": 3,
          "title": "内存考虑(去重复过程中，是想要空间复杂度最低吗？)",
          "slug": "内存考虑-去重复过程中-是想要空间复杂度最低吗"
        },
        {
          "level": 2,
          "title": "补充说明第三方库lodash",
          "slug": "补充说明第三方库lodash"
        },
        {
          "level": 3,
          "title": "lodash 如何实现去重",
          "slug": "lodash-如何实现去重"
        },
        {
          "level": 2,
          "title": "总结",
          "slug": "总结"
        },
        {
          "level": 2,
          "title": "参考文章",
          "slug": "参考文章"
        },
        {
          "level": 3,
          "title": "关注我",
          "slug": "关注我"
        },
        {
          "level": 3,
          "title": "Node系列原创文章",
          "slug": "node系列原创文章"
        }
      ]
    },
    {
      "title": "react 开源项目整理",
      "frontmatter": {},
      "regularPath": "/webframe/react/",
      "relativePath": "webframe/react/README.md",
      "key": "v-304c8972",
      "path": "/webframe/react/",
      "headers": [
        {
          "level": 2,
          "title": "react 开源项目整理",
          "slug": "react-开源项目整理"
        }
      ]
    },
    {
      "frontmatter": {},
      "regularPath": "/webframe/tool/",
      "relativePath": "webframe/tool/README.md",
      "key": "v-041f72e4",
      "path": "/webframe/tool/",
      "headers": [
        {
          "level": 2,
          "title": "常用软件下载",
          "slug": "常用软件下载"
        },
        {
          "level": 2,
          "title": "交流群讨论问题整理",
          "slug": "交流群讨论问题整理"
        }
      ]
    },
    {
      "title": "无形中提高你工作效率的chrome插件",
      "frontmatter": {
        "title": "无形中提高你工作效率的chrome插件",
        "date": "2020-05-15T00:00:00.000Z",
        "tags": [
          "工具",
          "chrome"
        ]
      },
      "regularPath": "/webframe/tool/chrome.html",
      "relativePath": "webframe/tool/chrome.md",
      "key": "v-69aa3fef",
      "path": "/webframe/tool/chrome.html",
      "headers": [
        {
          "level": 2,
          "title": "开发相关拓展插件",
          "slug": "开发相关拓展插件"
        },
        {
          "level": 3,
          "title": "1. WEB前端助手（FeHelper)",
          "slug": "_1-web前端助手-fehelper"
        },
        {
          "level": 3,
          "title": "2. vue-devtools",
          "slug": "_2-vue-devtools"
        },
        {
          "level": 3,
          "title": "3. React Developer Tools",
          "slug": "_3-react-developer-tools"
        },
        {
          "level": 3,
          "title": "4. Postman",
          "slug": "_4-postman"
        },
        {
          "level": 3,
          "title": "5. Octotree",
          "slug": "_5-octotree"
        },
        {
          "level": 3,
          "title": "6. Lighthouse 前端性能优化测试工具",
          "slug": "_6-lighthouse-前端性能优化测试工具"
        },
        {
          "level": 3,
          "title": "7. Clear Cache",
          "slug": "_7-clear-cache"
        },
        {
          "level": 3,
          "title": "8. Vimium",
          "slug": "_8-vimium"
        },
        {
          "level": 3,
          "title": "9. Save All Resources",
          "slug": "_9-save-all-resources"
        },
        {
          "level": 3,
          "title": "10. Wappalyzer",
          "slug": "_10-wappalyzer"
        },
        {
          "level": 2,
          "title": "日常高频使用（非开发类）",
          "slug": "日常高频使用-非开发类"
        },
        {
          "level": 3,
          "title": "1. 谷歌上网助手_GHelper",
          "slug": "_1-谷歌上网助手-ghelper"
        },
        {
          "level": 3,
          "title": "2. SimilarWeb",
          "slug": "_2-similarweb"
        },
        {
          "level": 3,
          "title": "3. Advertising Terminator",
          "slug": "_3-advertising-terminator"
        },
        {
          "level": 3,
          "title": "4. Infinity 新标签页",
          "slug": "_4-infinity-新标签页"
        },
        {
          "level": 3,
          "title": "5. 新媒体管家——帐号管理&图文编辑",
          "slug": "_5-新媒体管家-帐号管理-图文编辑"
        },
        {
          "level": 3,
          "title": "6. Extension Manager 扩展管理器",
          "slug": "_6-extension-manager-扩展管理器"
        },
        {
          "level": 2,
          "title": "获取及安装",
          "slug": "获取及安装"
        },
        {
          "level": 2,
          "title": "最后",
          "slug": "最后"
        }
      ]
    },
    {
      "title": "如何进阶成公司 Git 小能手(常见问题总结)",
      "frontmatter": {
        "title": "如何进阶成公司 Git 小能手(常见问题总结)",
        "date": "2020-03-15T00:00:00.000Z",
        "tags": [
          "工具",
          "git"
        ]
      },
      "regularPath": "/webframe/tool/git.html",
      "relativePath": "webframe/tool/git.md",
      "key": "v-faa79fce",
      "path": "/webframe/tool/git.html",
      "headers": [
        {
          "level": 2,
          "title": "前言",
          "slug": "前言"
        },
        {
          "level": 2,
          "title": "Git 经典图",
          "slug": "git-经典图"
        },
        {
          "level": 3,
          "title": "图中的几个专用名词解释：",
          "slug": "图中的几个专用名词解释"
        },
        {
          "level": 2,
          "title": "git 提交可能遇到的一些问题",
          "slug": "git-提交可能遇到的一些问题"
        },
        {
          "level": 3,
          "title": "git 想丢弃还没有到暂存区的代码修改，不想一个一个去撤销代码，把当前所有修改代码丢弃",
          "slug": "git-想丢弃还没有到暂存区的代码修改-不想一个一个去撤销代码-把当前所有修改代码丢弃"
        },
        {
          "level": 3,
          "title": "git 已经提交",
          "slug": "git-已经提交"
        },
        {
          "level": 3,
          "title": "git 提交到本地仓库有问题怎么办？",
          "slug": "git-提交到本地仓库有问题怎么办"
        },
        {
          "level": 3,
          "title": "Git 代码已经 push 上去发现有问题",
          "slug": "git-代码已经-push-上去发现有问题"
        },
        {
          "level": 2,
          "title": "Git 关于暂存的问题",
          "slug": "git-关于暂存的问题"
        },
        {
          "level": 2,
          "title": "Git 分支相关问题",
          "slug": "git-分支相关问题"
        },
        {
          "level": 3,
          "title": "问题1：我想把本地创建的一个分支 koalanode提交到远程，并且远程分支名称要求 nodescript，且还未创建，需要怎能做？",
          "slug": "问题1-我想把本地创建的一个分支-koalanode提交到远程-并且远程分支名称要求-nodescript-且还未创建-需要怎能做"
        },
        {
          "level": 2,
          "title": "git 用户名密码邮箱相关问题",
          "slug": "git-用户名密码邮箱相关问题"
        },
        {
          "level": 3,
          "title": "公司仓库有账号密码，自己的github有账户密码，两个不同账户，有一次提交发现自己仓库的邮箱提交成了公司仓库设置的邮箱，有点尴尬，为什么会出现这种问题呢？",
          "slug": "公司仓库有账号密码-自己的github有账户密码-两个不同账户-有一次提交发现自己仓库的邮箱提交成了公司仓库设置的邮箱-有点尴尬-为什么会出现这种问题呢"
        },
        {
          "level": 3,
          "title": "为什么我每次提交都需要输入github的密码，这个步骤如何省去？",
          "slug": "为什么我每次提交都需要输入github的密码-这个步骤如何省去"
        },
        {
          "level": 2,
          "title": "提交相关问题",
          "slug": "提交相关问题"
        },
        {
          "level": 2,
          "title": "几个开发中常用的命令没有做分类",
          "slug": "几个开发中常用的命令没有做分类"
        },
        {
          "level": 2,
          "title": "关于 merge 可能出现的问题",
          "slug": "关于-merge-可能出现的问题"
        },
        {
          "level": 2,
          "title": "git 工作流",
          "slug": "git-工作流"
        },
        {
          "level": 2,
          "title": "git 提交规范",
          "slug": "git-提交规范"
        },
        {
          "level": 2,
          "title": "Git 工具",
          "slug": "git-工具"
        },
        {
          "level": 2,
          "title": "vim 常用命令",
          "slug": "vim-常用命令"
        },
        {
          "level": 2,
          "title": "总结",
          "slug": "总结"
        }
      ]
    },
    {
      "title": "node以往的版本",
      "frontmatter": {
        "tags": [
          "工具"
        ]
      },
      "regularPath": "/webframe/tool/node-versions.html",
      "relativePath": "webframe/tool/node-versions.md",
      "key": "v-ac75dc4e",
      "path": "/webframe/tool/node-versions.html",
      "headers": [
        {
          "level": 2,
          "title": "node以往的版本",
          "slug": "node以往的版本"
        }
      ]
    },
    {
      "title": "我常用的前端提效 shell 命令",
      "frontmatter": {
        "title": "我常用的前端提效 shell 命令",
        "date": "2020-07-06T00:00:00.000Z",
        "tags": [
          "shell",
          "工具"
        ]
      },
      "regularPath": "/webframe/tool/shell.html",
      "relativePath": "webframe/tool/shell.md",
      "key": "v-5e31e419",
      "path": "/webframe/tool/shell.html",
      "headers": [
        {
          "level": 2,
          "title": "curl",
          "slug": "curl"
        },
        {
          "level": 3,
          "title": "常用的结果参数",
          "slug": "常用的结果参数"
        },
        {
          "level": 3,
          "title": "curl 项目中应用",
          "slug": "curl-项目中应用"
        },
        {
          "level": 2,
          "title": "vim 中的基本操作和配置",
          "slug": "vim-中的基本操作和配置"
        },
        {
          "level": 3,
          "title": "非 insert 模式",
          "slug": "非-insert-模式"
        },
        {
          "level": 3,
          "title": "insert 模式",
          "slug": "insert-模式"
        },
        {
          "level": 2,
          "title": "ping",
          "slug": "ping"
        },
        {
          "level": 3,
          "title": "应用",
          "slug": "应用"
        },
        {
          "level": 3,
          "title": "学会看懂出错提示信息",
          "slug": "学会看懂出错提示信息"
        },
        {
          "level": 2,
          "title": "telnet",
          "slug": "telnet"
        },
        {
          "level": 3,
          "title": "使用 telnet ip port",
          "slug": "使用-telnet-ip-port"
        },
        {
          "level": 2,
          "title": "总结",
          "slug": "总结"
        }
      ]
    },
    {
      "title": "使用Vuepress搭建博客",
      "frontmatter": {
        "title": "使用Vuepress搭建博客",
        "date": "2020-05-20T00:00:00.000Z",
        "tags": [
          "工具",
          "Vue",
          "Vuepress"
        ]
      },
      "regularPath": "/webframe/tool/vuepressBlog.html",
      "relativePath": "webframe/tool/vuepressBlog.md",
      "key": "v-19f272a5",
      "path": "/webframe/tool/vuepressBlog.html",
      "headers": [
        {
          "level": 2,
          "title": "为什么选择vuepress",
          "slug": "为什么选择vuepress"
        },
        {
          "level": 3,
          "title": "vuepress特性",
          "slug": "vuepress特性"
        },
        {
          "level": 2,
          "title": "项目搭建",
          "slug": "项目搭建"
        },
        {
          "level": 3,
          "title": "安装vuepress",
          "slug": "安装vuepress"
        },
        {
          "level": 3,
          "title": "初始化项目",
          "slug": "初始化项目"
        },
        {
          "level": 2,
          "title": "页面具体内容配置",
          "slug": "页面具体内容配置"
        },
        {
          "level": 3,
          "title": "基本配置",
          "slug": "基本配置"
        },
        {
          "level": 3,
          "title": "设置封面页",
          "slug": "设置封面页"
        },
        {
          "level": 3,
          "title": "配置导航栏nav",
          "slug": "配置导航栏nav"
        },
        {
          "level": 3,
          "title": "配置侧边栏slider",
          "slug": "配置侧边栏slider"
        },
        {
          "level": 2,
          "title": "自定义布局内容",
          "slug": "自定义布局内容"
        },
        {
          "level": 3,
          "title": "配置插件",
          "slug": "配置插件"
        },
        {
          "level": 3,
          "title": "UI插件",
          "slug": "ui插件"
        },
        {
          "level": 3,
          "title": "支持PWA",
          "slug": "支持pwa"
        },
        {
          "level": 3,
          "title": "配置评论",
          "slug": "配置评论"
        },
        {
          "level": 3,
          "title": "主题样式修改",
          "slug": "主题样式修改"
        },
        {
          "level": 2,
          "title": "部署",
          "slug": "部署"
        },
        {
          "level": 3,
          "title": "nginx部署",
          "slug": "nginx部署"
        },
        {
          "level": 3,
          "title": "github部署",
          "slug": "github部署"
        },
        {
          "level": 2,
          "title": "项目地址",
          "slug": "项目地址"
        }
      ]
    },
    {
      "title": "vue中8种组件通信方式",
      "frontmatter": {
        "title": "vue中8种组件通信方式",
        "date": "2019-06-11T00:00:00.000Z",
        "tags": [
          "Vue",
          "Vuex",
          "通信方式"
        ]
      },
      "regularPath": "/webframe/vue/messageWays.html",
      "relativePath": "webframe/vue/messageWays.md",
      "key": "v-7e68ea66",
      "path": "/webframe/vue/messageWays.html",
      "headers": [
        {
          "level": 2,
          "title": "一、props / $emit",
          "slug": "一、props-emit"
        },
        {
          "level": 2,
          "title": "二、  $children / $parent",
          "slug": "二、-children-parent"
        },
        {
          "level": 2,
          "title": "三、provide/ inject",
          "slug": "三、provide-inject"
        },
        {
          "level": 2,
          "title": "四、ref / refs",
          "slug": "四、ref-refs"
        },
        {
          "level": 2,
          "title": "五、eventBus",
          "slug": "五、eventbus"
        },
        {
          "level": 2,
          "title": "六、Vuex",
          "slug": "六、vuex"
        },
        {
          "level": 2,
          "title": "七、 localStorage / sessionStorage",
          "slug": "七、localstorage-sessionstorage"
        },
        {
          "level": 2,
          "title": "八 $attrs与 $listeners",
          "slug": "八-attrs与-listeners"
        },
        {
          "level": 2,
          "title": "总结",
          "slug": "总结-2"
        }
      ]
    },
    {
      "title": "vue开源项目",
      "frontmatter": {},
      "regularPath": "/webframe/vue/",
      "relativePath": "webframe/vue/readme.md",
      "key": "v-3a3c125c",
      "path": "/webframe/vue/",
      "headers": [
        {
          "level": 2,
          "title": "vue开源项目",
          "slug": "vue开源项目"
        }
      ]
    }
  ],
  "themeConfig": {}
}